### Evaluation + Exploration of the LangChain Chatbot Output
This notebook compares the output on various queries to make sure the langchain model is functioning correctly and incorporating API context, not just returning information directly from openai.</br></br>

In [1]:
#IMPORTS
'''Specific versions of LangChain needed to run Ragas - different from needed for LangChain for Chatbot'''
#! pip install langchain-openai==0.0.2
#! pip install langchain-core==0.1.45
import time
import sys
sys.path.insert(0,'../')
from environment import env
config = env.env()

OPENAI_API_KEY = config['gpt_api_key']
import os
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

from langchain_openai import ChatOpenAI
from langchain.schema.messages import HumanMessage, SystemMessage
#from langchain.memory.buffer import ConversationBufferMemory
#from langchain.prompts import (
#    ChatPromptTemplate,
#)"""

from model_functions.gnb_model import *
from model_functions.get_context import *
from model_functions.get_context import parsed_context
from model_functions.lang_chatbot import nps_chain

import nest_asyncio
import openai
openai.api_key = OPENAI_API_KEY
nest_asyncio.apply()

#from langchain.chains import RetrievalQA
from ragas.metrics import answer_similarity
from ragas import evaluate
from datasets import Dataset

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/lauralyns/Documents/MADS/SIADS 699 -
[nltk_data]     Capstone/Capstone
[nltk_data]     VS/MADS_Capstone/.venv/lib/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/lauralyns/Documents/MADS/SIADS 699 -
[nltk_data]     Capstone/Capstone
[nltk_data]     VS/MADS_Capstone/.venv/lib/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/lauralyns/Documents/MADS/SIADS 699 -
[nltk_data]     Capstone/Capstone
[nltk_data]     VS/MADS_Capstone/.venv/lib/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

'\nfrom langchain.chains import RetrievalQA\nfrom ragas.metrics import answer_similarity\nfrom ragas import evaluate\n#from ragas.langchain.evalchain import RagasEvaluatorChain\nfrom ragas.metrics import (\n    faithfulness,\n    answer_relevancy,\n    context_precision,\n    context_recall,\n)\nfrom datasets import Dataset\n'

In [2]:
#VARIABLES
model = gnb_model
chat_model = ChatOpenAI(model="gpt-3.5-turbo-0125", temperature=0,api_key  = OPENAI_API_KEY)

In [217]:
#costs
gpt3 = .03/20
embed = .01/28
gpt3 *4000 + embed*2000

pre_calls = 25.38
gpt_100 = 25.39 - 25.38
lang_100 = 25.48 - 25.39

gpt_lang_100 = 25.59 - 25.39

gpt_100 = 0.0
lang_100 = 25.62 - 25.59

gpt_200 = 25.72 - 25.59
lang_200 = 25.90 - 25.72


gpt_lang_250 = 26.21 - 25.90
gpt_lang_to_1100 = 26.71 - 26.21

miscalculate = 27.24 - 26.74

gpt_to_2000ish = - 27.24

6.714285714285714

In [2]:
#Time for calls
test_100 = 50 * 60
break_len = 1000 #seconds
timing_100 = test_100  - break_len * 3
timing_100
#5 min?

0

#### Chat Models
Defining Chat models to be easily invoked for this testing context

In [18]:
def gpt_chat(query, intent="", endpoint="", parkcode=""):
    """Takes Question as input and returns the result of running it through the generic chat_model used for reference
    intent, endpoint and parkcode included so that it can be invoked in same way as other models"""
    messages = [
        SystemMessage(content="""You're an assistant knowledgeable about national parks. Only answer national park related questions."""),
        HumanMessage(content=query),]
    return chat_model.invoke(messages).content

In [19]:
gpt_chat("What is yosemite like")

"Yosemite National Park is located in California's Sierra Nevada mountains and is known for its stunning granite cliffs, waterfalls, giant sequoia trees, and diverse wildlife. The park offers a variety of outdoor activities such as hiking, rock climbing, camping, and wildlife viewing. Yosemite Valley is a popular destination within the park, known for iconic landmarks like El Capitan and Half Dome."

In [12]:
def lang_chat(query, intent, endpoint, parkcode):
    """Takes Question as input and returns the result of running it through LangChain promp templat chat model (nps_chain.py) 
    Instead of using get_context(question, model) for context as usual, the correct API landing page is handed through as context with 
    call_api() function which uses intent, endpoint and parkcode from test data to ensure that the correct context is referenced. 
    Returns model results"""
    return nps_chain.invoke({"context": call_api(endpoint, parkcode, intent), "question": query})

In [13]:
lang_chat("What is yosemite like", "description", "parks", "yose")

'Yosemite National Park is not just a great valley, but a shrine to human foresight, the strength of granite, the power of glaciers, the persistence of life, and the tranquility of the High Sierra. It is best known for its waterfalls, but within its nearly 1,200 square miles, you can find deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area, and much more.'

In [15]:
def ground_truth(query, intent, endpoint, parkcode):
    """Takes in the intent, endpoint and parkcode from test data and runs through parsed_context() to find context from NPS webpage
    Returns the ground_truth context from the correct API call, to be compared against by the other models"""
    return parsed_context(endpoint, parkcode, intent)

In [16]:
ground_truth('', 'description', 'parks', 'yose')

'Not just a great valley, but a shrine to human foresight, the strength of granite, the power of glaciers, the persistence of life, and the tranquility of the High Sierra. First protected in 1864, Yosemite National Park is best known for its waterfalls, but within its nearly 1,200 square miles, you can find deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area, and much more.'

In [6]:
models = {
    'gpt_chat' : gpt_chat,
    'lang_chat': lang_chat,
    'ground_truth': ground_truth,
}

##### Test Data
Constructing Test Data set, and making sure it is representative

In [7]:
test_data = pd.read_csv('../02_nps_api_data/testing_queries.csv')
test_data.columns = ['query', 'intent', 'endpoint', 'parkcode']
test_data = test_data.sample(3000, random_state=42)
test_data.head()

,query,intent,endpoint,parkcode
27641,What are the fees for visiting Virgin Islands ...,feespass,feespasses,vicr
15777,What is available at Denali National Park & Pr...,amenities,amenities,dena
24454,What events are scheduled at Lower Delaware?,events,events,lode
6328,What is the address of Saint Paul's Church,address,parks,sapa
28771,What are the fees for visiting Grant-Kohrs Ranch,feespass,feespasses,grko

In [ ]:
#compare % of each for test data versus sample of data?

In [8]:
test_data['intent'].value_counts()

intent
amenities      582
events         499
alerts         476
feespass       438
description    353
fullname       296
address        264
state           92
Name: count, dtype: int64

In [9]:
test_data['endpoint'].value_counts()

endpoint
parks         1005
amenities      582
events         499
alerts         476
feespasses     438
Name: count, dtype: int64

In [10]:
test_data['parkcode'].value_counts()

parkcode
lowe    15
fopu    14
wwii    13
cahi    12
foun    12
        ..
arpo     2
kaww     2
flni     2
mana     1
misp     1
Name: count, Length: 471, dtype: int64

#### Comparing Context to Results

In [11]:
def add_responses(query_df, chat_models, n=0):
    """Adds the responses for given chat models to the dataframe of questions, intents, parkcodes and queries, and saves as pickle"""
    while n < len(query_df):
        segment_time = []
        segment_df = query_df[n:n+400]

        for model in chat_models:
            start = time.time()
            temp_df = segment_df.apply(lambda x: chat_models[model](x['query'],x['intent'],x['endpoint'],x['parkcode']), axis=1)
            stop = time.time()

            temp_df = pd.DataFrame(temp_df, columns = [model])
            segment_df = pd.concat([segment_df, temp_df], axis=1)
            segment_df = segment_df.fillna('none')
        
            segment_time.append((stop-start)/len(segment_df))
            #Sleeps for 1 hr so that NPS can be called again and does not go over NPS API limit of 1000 requests / hour
            #time.sleep(3600)
     
        if n ==0:
            test_df = segment_df
            times = pd.DataFrame(columns=chat_models.keys())
        else:
            test_df = pd.read_pickle('chat_test.pkl')
            test_df = pd.concat([test_df, segment_df], axis=0)
            times = pd.read_pickle('chat_times.pkl')
            
        times.loc[n] = segment_time
        test_df.to_pickle('chat_test.pkl')
        times.to_pickle('chat_times.pkl')
        n=n+400
        print(n, 'completed')

In [29]:
#Uncomment to run if chat_test.pkl does not exist. Otherwise takes x hours and costs ~$x money to run per k of data
#add_responses(test_data[0:2000], models, 1101)

In [ ]:
#Completed:
#0-100
#100-200
#200-400
#400-650
#650-1100

In [12]:
responses = pd.read_pickle('chat_test.pkl')
responses

,query,intent,endpoint,parkcode,gpt_chat,lang_chat,ground_truth
27641,What are the fees for visiting Virgin Islands ...,feespass,feespasses,vicr,There are no entrance fees for visiting Virgin...,Virgin Islands Coral Reef National Monument is...,Interagency Pass is not accepted.
15777,What is available at Denali National Park & Pr...,amenities,amenities,dena,"Denali National Park & Preserve, located in Al...",Denali National Park & Preserve offers a varie...,"Accessible Rooms, Assistive Listening Systems,..."
24454,What events are scheduled at Lower Delaware?,events,events,lode,"I'm sorry, but there is no national park calle...",Lower Delaware National Wild and Scenic River ...,No events information found
6328,What is the address of Saint Paul's Church,address,parks,sapa,"I'm sorry, I can only provide information abou...",The address of Saint Paul's Church National Hi...,"897 South Columbus Avenue, Mount Vernon, NY, 1..."
28771,What are the fees for visiting Grant-Kohrs Ranch,feespass,feespasses,grko,The entrance fee for Grant-Kohrs Ranch Nationa...,"Grant-Kohrs Ranch is a fee-free park, so there...",Interagency Pass is not accepted.
...,...,...,...,...,...,...,...
30025,How much is a ticket for Washington Monument?,feespass,feespasses,wamo,The Washington Monument is not a national park...,A ticket for the Washington Monument costs $1.00.,Interagency Pass is not accepted. There is no ...
20117,What services are there at Richmond Park?,amenities,amenities,rich,Richmond Park is a royal park located in Londo...,Richmond Park is a national park located in Lo...,No amenities information found
1660,Give me information on Theodore Roosevelt Inau...,description,parks,thri,Theodore Roosevelt Inaugural National Historic...,Theodore Roosevelt Inaugural National Historic...,"As president, Theodore Roosevelt created prote..."
499,Give me information on Edgar Allan Poe Nationa...,description,parks,edal,"I'm sorry, but there is no national park calle...",The Edgar Allan Poe National Historic Site is ...,"Described as horrifying, mystifying, and brill..."
14545,List any alerts for Puʻukoholā Heiau?,alerts,alerts,puhe,"As of now, there are no alerts or closures rep...",There are two alerts for Pu'ukoholā Heiau Nati...,Pu'ukoholā Heiau NHS Visitor Center and Museum...

In [23]:
len(responses)

1100

In [24]:
responses.duplicated(subset=['query']).value_counts()

False    1097
True        3
Name: count, dtype: int64

In [15]:
responses[responses.duplicated(subset=['query'],keep=False)]

,query,intent,endpoint,parkcode,gpt_chat,lang_chat,ground_truth
16565,What services are there at Kenai Fjords Nation...,amenities,amenities,kefj,"At Kenai Fjords National Park, visitors can en...",Kenai Fjords National Park offers services suc...,"Accessible Sites, Assistive Listening Systems,..."
26425,How much is a ticket for Great Egg Harbor River?,feespass,feespasses,greg,"Entrance to Great Egg Harbor River is free, as...",There is no entrance fee for Great Egg Harbor ...,Interagency Pass is not accepted.
28780,How much is a ticket for Great Egg Harbor River?,feespass,feespasses,greg,There is no entrance fee for Great Egg Harbor ...,There is no entrance fee for Great Egg Harbor ...,Interagency Pass is not accepted.
17754,What services are there at Washington Monument?,amenities,amenities,wamo,The Washington Monument is not a national park...,"I'm sorry, but I don't have information on the...","Bicycle - Rental, Gifts/Souvenirs/Books, Histo..."
16560,What services are there at Kenai Fjords Nation...,amenities,amenities,kefj,"At Kenai Fjords National Park, visitors can en...",Kenai Fjords National Park offers services suc...,"Accessible Sites, Assistive Listening Systems,..."
20585,What services are there at Washington Monument?,amenities,amenities,wamo,The Washington Monument is not a national park...,"I'm sorry, but I don't have information on the...","Bicycle - Rental, Gifts/Souvenirs/Books, Histo..."

In [61]:
def ragas_similarity(answer, context):
    """Converts answer and ground truth into a hugging face dataset so that answer similarity between the 2 can be calculated
    While RAGAS could be used to find the average answer similarities for the whole dataframe, this would not give case by case
        information on where the models are performing better or worse than one another etc.
    Input: anser = results returned from a model
        context = the context returned from API that should be compared against
    Output: score = the answer similarity score (cosine similarity) between answer and context as calculated by RAGAS """
    d1 = {
        "answer": [answer],
        "ground_truth": [context],
        }
    dataset1 = Dataset.from_dict(d1)
    scores = evaluate(dataset1, metrics=[answer_similarity])
    score = scores['answer_similarity']
    return score

In [30]:
def add_answer_similarity(query_df, chat_models, n=0):
    """ Adds answer similarity calculations to a dataframe of chat model responses and contexts (ground_truths)
    Input: query_df = dataframe 
        chat_models = list of model names (or dict with model names as keys) to be used for identifying columns to use as the model 'answers'
        n = counter for if this needs to be run in chunks or started part way through"""
    while n < len(query_df):
        segment_df = query_df[n:n+20]

        for model in chat_models:
            temp_df = segment_df.apply(lambda x: ragas_similarity(x[model],x['ground_truth']), axis=1)
            temp_df = pd.DataFrame(temp_df, columns = [f'{model}_sim'])
            segment_df = pd.concat([segment_df, temp_df], axis=1)
            segment_df = segment_df.fillna('none')
     
        if n ==0:
            test_df = segment_df
        else:
            test_df = pd.read_pickle('similarity.pkl')
            test_df = pd.concat([test_df, segment_df], axis=0)
            
        test_df.to_pickle('similarity.pkl')
        n=n+20
        print(n, 'completed')

In [77]:
##Uncomment to run if similarity.pkl does not exist. Otherwise takes >1 hour to run.
#add_answer_similarity(responses[:1100], ['lang_chat', 'gpt_chat'], 620)

In [ ]:
#Completed:
#0-100
#100-400 -- 8 min
#400-620
#620-1100

In [18]:
similarity = pd.read_pickle('similarity.pkl')
similarity

,query,intent,endpoint,parkcode,gpt_chat,lang_chat,ground_truth,lang_chat_sim,gpt_chat_sim
27641,What are the fees for visiting Virgin Islands ...,feespass,feespasses,vicr,There are no entrance fees for visiting Virgin...,Virgin Islands Coral Reef National Monument is...,Interagency Pass is not accepted.,0.735420,0.738262
15777,What is available at Denali National Park & Pr...,amenities,amenities,dena,"Denali National Park & Preserve, located in Al...",Denali National Park & Preserve offers a varie...,"Accessible Rooms, Assistive Listening Systems,...",0.903771,0.779647
24454,What events are scheduled at Lower Delaware?,events,events,lode,"I'm sorry, but there is no national park calle...",Lower Delaware National Wild and Scenic River ...,No events information found,0.748020,0.744912
6328,What is the address of Saint Paul's Church,address,parks,sapa,"I'm sorry, I can only provide information abou...",The address of Saint Paul's Church National Hi...,"897 South Columbus Avenue, Mount Vernon, NY, 1...",0.911092,0.709546
28771,What are the fees for visiting Grant-Kohrs Ranch,feespass,feespasses,grko,The entrance fee for Grant-Kohrs Ranch Nationa...,"Grant-Kohrs Ranch is a fee-free park, so there...",Interagency Pass is not accepted.,0.746890,0.745062
...,...,...,...,...,...,...,...,...,...
30025,How much is a ticket for Washington Monument?,feespass,feespasses,wamo,The Washington Monument is not a national park...,A ticket for the Washington Monument costs $1.00.,Interagency Pass is not accepted. There is no ...,0.882758,0.901474
20117,What services are there at Richmond Park?,amenities,amenities,rich,Richmond Park is a royal park located in Londo...,Richmond Park is a national park located in Lo...,No amenities information found,0.733472,0.736993
1660,Give me information on Theodore Roosevelt Inau...,description,parks,thri,Theodore Roosevelt Inaugural National Historic...,Theodore Roosevelt Inaugural National Historic...,"As president, Theodore Roosevelt created prote...",0.860418,0.864725
499,Give me information on Edgar Allan Poe Nationa...,description,parks,edal,"I'm sorry, but there is no national park calle...",The Edgar Allan Poe National Historic Site is ...,"Described as horrifying, mystifying, and brill...",0.890917,0.859263
14545,List any alerts for Puʻukoholā Heiau?,alerts,alerts,puhe,"As of now, there are no alerts or closures rep...",There are two alerts for Pu'ukoholā Heiau Nati...,Pu'ukoholā Heiau NHS Visitor Center and Museum...,0.961931,0.904686

In [19]:
len(similarity)

1100

In [20]:
similarity.duplicated(subset=['query']).value_counts()

False    1097
True        3
Name: count, dtype: int64

In [21]:
similarity.tail()

,query,intent,endpoint,parkcode,gpt_chat,lang_chat,ground_truth,lang_chat_sim,gpt_chat_sim
30025,How much is a ticket for Washington Monument?,feespass,feespasses,wamo,The Washington Monument is not a national park...,A ticket for the Washington Monument costs $1.00.,Interagency Pass is not accepted. There is no ...,0.882758,0.901474
20117,What services are there at Richmond Park?,amenities,amenities,rich,Richmond Park is a royal park located in Londo...,Richmond Park is a national park located in Lo...,No amenities information found,0.733472,0.736993
1660,Give me information on Theodore Roosevelt Inau...,description,parks,thri,Theodore Roosevelt Inaugural National Historic...,Theodore Roosevelt Inaugural National Historic...,"As president, Theodore Roosevelt created prote...",0.860418,0.864725
499,Give me information on Edgar Allan Poe Nationa...,description,parks,edal,"I'm sorry, but there is no national park calle...",The Edgar Allan Poe National Historic Site is ...,"Described as horrifying, mystifying, and brill...",0.890917,0.859263
14545,List any alerts for Puʻukoholā Heiau?,alerts,alerts,puhe,"As of now, there are no alerts or closures rep...",There are two alerts for Pu'ukoholā Heiau Nati...,Pu'ukoholā Heiau NHS Visitor Center and Museum...,0.961931,0.904686

Similarity Scores

In [75]:
lang_chat_avg = similarity['lang_chat_sim'].mean()
gpt_chat_avg = similarity['gpt_chat_sim'].mean()
print('Average Similarity score for LangChain Model with context: ', lang_chat_avg)
print('Average Similarity score for GPT Model with no context: ', gpt_chat_avg)

Average Similarity score for LangChain Model with context:  0.8639427709871653
Average Similarity score for GPT Model with no context:  0.8294172795530692

In [76]:
#Frequency Better
lang_better = len(similarity.query('lang_chat_sim>=gpt_chat_sim'))
gpt_beter = len(similarity) - lang_better
percent = (lang_better / len(similarity))*100
print(f'The Langchain Model performs better than the GPT model {lang_better} times')
print(f'The Langchain Model performs worse than the GPT model {gpt_beter} times')
print(f'The Langchain Model performs better than the GPT model in {percent}% of test cases')

The Langchain Model performs better than the GPT model 854 times
The Langchain Model performs worse than the GPT model 246 times
The Langchain Model performs better than the GPT model in 77.63636363636364% of test cases

In [25]:
intents = similarity.groupby('intent').agg({'lang_chat_sim': 'mean', 'gpt_chat_sim': 'mean'})
intents

             lang_chat_sim  gpt_chat_sim
intent
address           0.872028      0.851595
alerts            0.874505      0.807152
amenities         0.839540      0.795280
description       0.935322      0.899247
events            0.835112      0.804329
feespass          0.837072      0.818407
fullname          0.927400      0.924069
state             0.674771      0.672171

In [26]:
endpoints = similarity.groupby('endpoint').agg({'lang_chat_sim': 'mean', 'gpt_chat_sim': 'mean'})
endpoints

            lang_chat_sim  gpt_chat_sim
endpoint
alerts           0.874505      0.807152
amenities        0.839540      0.795280
events           0.835112      0.804329
feespasses       0.837072      0.818407
parks            0.896681      0.876552

In [27]:
parkcodes = similarity.groupby('parkcode').agg({'lang_chat_sim': 'mean', 'gpt_chat_sim': 'mean'})
parkcodes['diff'] = parkcodes['lang_chat_sim'] - parkcodes['gpt_chat_sim']
parkcodes.sort_values(by = 'diff', ascending=False).head()

          lang_chat_sim  gpt_chat_sim      diff
parkcode
sapa           0.911092      0.709546  0.201546
kova           0.954950      0.758636  0.196314
tuin           0.969368      0.797505  0.171862
gree           0.934047      0.771159  0.162888
deto           0.946552      0.792275  0.154278

In [28]:
parkcodes.sort_values(by = 'diff', ascending=False).tail()

          lang_chat_sim  gpt_chat_sim      diff
parkcode
nico           0.804178      0.838669 -0.034491
whho           0.734040      0.769413 -0.035373
bowa           0.786850      0.824431 -0.037581
mono           0.772792      0.811028 -0.038236
kowa           0.778689      0.828314 -0.049626

Time Comparison

In [28]:
timer = pd.read_pickle('chat_times.pkl')
mean_times = pd.DataFrame(timer.mean()).reset_index()
mean_times.columns = ['Model','Average Seconds per Call']
mean_times

          Model  Average Seconds per Call
0      gpt_chat                  1.150051
1     lang_chat                  1.670762
2  ground_truth                  0.530556

#### Exploration
Examples of calls for each intent, comparing Context returned, LangChain Model with Context, and directly asking GPT model<br>
'lang_chat' is redefined to use GNB model underneath to simulate real world use<br>
'get_context' returns the direct API call, rather than the 'parsed_context' in evaluation above<br>

In [32]:
def lang_chat(query):
    """Takes Question as input and returns the result of running it through LangChain promp templat chat model (nps_chain.py) 
    Usesing get_context(query, model) for context as usual, the correct API landing page is handed through as context with 
    call_api() function which uses intent, endpoint and parkcode from test data to ensure that the correct context is referenced. 
    Returns model results"""
    return nps_chain.invoke({"context": get_context(query, model), "question": query})

##### Description

In [149]:
question = "Describe Yosemite"
get_context(question, model)

[{'id': '4324B2B4-D1A3-497F-8E6B-27171FAE4DB2',
  'url': 'https://www.nps.gov/yose/index.htm',
  'fullName': 'Yosemite National Park',
  'parkCode': 'yose',
  'description': 'Not just a great valley, but a shrine to human foresight, the strength of granite, the power of glaciers, the persistence of life, and the tranquility of the High Sierra. First protected in 1864, Yosemite National Park is best known for its waterfalls, but within its nearly 1,200 square miles, you can find deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area, and much more.',
  'latitude': '37.84883288',
  'longitude': '-119.5571873',
  'latLong': 'lat:37.84883288, long:-119.5571873',
  'activities': [{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42',
    'name': 'Arts and Culture'},
   {'id': '5F723BAD-7359-48FC-98FA-631592256E35', 'name': 'Auto and ATV'},
   {'id': '0B4A5320-216D-451A-9990-626E1D5ACE28', 'name': 'Scenic Driving'},
   {'id': '13A57703-BB1A-41A2-94B8-53B692EB7238', 'name': 'Astronomy'},
   {'id': '7CE6E935-F839-4FEC-A63E-052B1DEF39D2', 'name': 'Biking'},
   {'id': '071BA73C-1D3C-46D4-A53C-00D5602F7F0E', 'name': 'Boating'},
   {'id': 'A59947B7-3376-49B4-AD02-C0423E08C5F7', 'name': 'Camping'},
   {'id': '4A58AF13-E8FB-4530-B41A-97DF0B0C77B7',
    'name': 'Backcountry Camping'},
   {'id': 'B12FAAB9-713F-4B38-83E4-A273F5A43C77', 'name': 'Climbing'},
   {'id': 'AE42B46C-E4B7-4889-A122-08FE180371AE', 'name': 'Fishing'},
   {'id': '1DFACD97-1B9C-4F5A-80F2-05593604799E', 'name': 'Food'},
   {'id': 'B33DC9B6-0B7D-4322-BAD7-A13A34C584A3', 'name': 'Guided Tours'},
   {'id': '42FD78B9-2B90-4AA9-BC43-F10E9FEA8B5A', 'name': 'Hands-On'},
   {'id': 'BFF8C027-7C8F-480B-A5F8-CD8CE490BFBA', 'name': 'Hiking'},
   {'id': '7C37B79B-D02D-49EB-9020-3DB8299B748A',
    'name': 'Backcountry Hiking'},
   {'id': '0307955A-B65C-4CE4-A780-EB36BAAADF0B', 'name': 'Horse Trekking'},
   {'id': '1886DA47-0AEC-4568-B9C2-8E9BC316AAAC', 'name': 'Horseback Riding'},
   {'id': '5FF5B286-E9C3-430E-B612-3380D8138600', 'name': 'Ice Skating'},
   {'id': 'B204DE60-5A24-43DD-8902-C81625A09A74', 'name': 'Living History'},
   {'id': '4D224BCA-C127-408B-AC75-A51563C42411', 'name': 'Paddling'},
   {'id': 'DF4A35E0-7983-4A3E-BC47-F37B872B0F25',
    'name': 'Junior Ranger Program'},
   {'id': '4D06CEED-90C6-4B69-B264-32CC90B69BA6', 'name': 'Tubing'},
   {'id': '67FDB577-518E-4A3E-B608-E78941116223', 'name': 'Snow Tubing'},
   {'id': 'F9B1D433-6B86-4804-AED7-B50A519A3B7C', 'name': 'Skiing'},
   {'id': 'C38B3C62-1BBF-4EA1-A1A2-35DE21B74C17', 'name': 'Snow Play'},
   {'id': '01D717BC-18BB-4FE4-95BA-6B13AD702038', 'name': 'Snowshoeing'},
   {'id': '587BB2D3-EC35-41B2-B3F7-A39E2B088AEE', 'name': 'Swimming'},
   {'id': '0B685688-3405-4E2A-ABBA-E3069492EC50', 'name': 'Wildlife Watching'},
   {'id': '5A2C91D1-50EC-4B24-8BED-A2E11A1892DF', 'name': 'Birdwatching'},
   {'id': '0C0D142F-06B5-4BE1-8B44-491B90F93DEB', 'name': 'Park Film'},
   {'id': 'C8F98B28-3C10-41AE-AA99-092B3B398C43', 'name': 'Museum Exhibits'},
   {'id': '24380E3F-AD9D-4E38-BF13-C8EEB21893E7', 'name': 'Shopping'},
   {'id': '467DC8B8-0B7D-436D-A026-80A22358F615',
    'name': 'Bookstore and Park Store'}],
  'topics': [{'id': '69693007-2DF2-4EDE-BB3B-A25EBA72BDF5',
    'name': 'Architecture and Building'},
   {'id': '28AEAE85-9DDA-45B6-981B-1CFCDCC61E14',
    'name': 'African American Heritage'},
   {'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B', 'name': 'Archeology'},
   {'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370', 'name': 'Arts'},
   {'id': '05B7868A-3F3C-433D-876E-A886C4BE7A12', 'name': 'Painting'},
   {'id': '9BD60DC0-C82B-42BA-A170-456B7423429D', 'name': 'Photography'},
   {'id': '227D2677-28CA-4CBF-997F-61108975A497',
    'name': 'Asian American Heritage'},
   {'id': '607D41B0-F830-4C07-A557-BCEF880A3929',
    'name': 'Burial, Cemetery and Gravesite'},
   {'id': 'A1BAF33E-EA84-4608-A888-4CEE9541F027',
    'name': 'Native American Heritage'},
   {'id': '518B32FB-339D-4C52-B2C2-04BF406AA4B0',
    'name': 'Religion and Spirituality'},
   {'id': '98F41FDF-B73F-4B68-8010-53CCB2891E3B', 'name': 'Churches'},
   {'id': '3CDB67A9-1EAC-408D-88EC-F26FA35E90AF',
    'name': 'Schools and Education'},
   {'id': 'D1CF31DE-AFED-412B-9425-DD1FD4CBB5C7',
    'name': 'Science, Technology and Innovation'},
   {'id': 'FE2C2613-B41E-4531-BC43-03EB6E45CBCF', 'name': 'Transportation'},
   {'id': 'A160B3D9-1603-4D89-B82F-21FCAF9EEE3B', 'name': 'Tragic Events'},
   {'id': 'D91B6F1A-FED8-490D-B181-9940474CD67C', 'name': 'Floods'},
   {'id': '7DA81DAB-5045-4953-9C20-36590AD9FA95', 'name': "Women's History"},
   {'id': '0D00073E-18C3-46E5-8727-2F87B112DDC6', 'name': 'Animals'},
   {'id': '957EF2BD-AC6C-4B7B-BD9A-87593ADC6691', 'name': 'Birds'},
   {'id': '2539614A-9646-446E-8251-34D3AAE068FA', 'name': 'Cats (wild)'},
   {'id': '1608649A-E7D7-4529-BD83-074C90F9FB68', 'name': 'Fish'},
   {'id': '4DC11D06-00F1-4A01-81D0-89CCCCE4FF50', 'name': 'Climate Change'},
   {'id': '04A39AB8-DD02-432F-AE5F-BA1267D41A0D', 'name': 'Fire'},
   {'id': '9F6A7003-59D6-4438-935F-760FD04C1073',
    'name': 'Foothills, Plains and Valleys'},
   {'id': '41B1A0A3-11FF-4F55-9CB9-034A7E28B087',
    'name': 'Forests and Woodlands'},
   {'id': 'F0F97E32-2F29-41B4-AF98-9FBE8DAB36B1', 'name': 'Geology'},
   {'id': 'FBB14C45-1663-4714-9D28-B2B99874644D', 'name': 'Glaciers'},
   {'id': '94262026-92F5-48E9-90EF-01CEAEFBA4FF', 'name': 'Grasslands'},
   {'id': 'AEA4C5FD-F25C-4C3D-97FE-2767ED3EE682', 'name': 'Meadows'},
   {'id': '1CF1F6BB-A037-445B-8CF2-81428E50CE52', 'name': 'Lakes'},
   {'id': '101F4D51-F99D-45A6-BBB6-CD481E5FACED', 'name': 'Mountains'},
   {'id': 'F8C2FE93-DEB3-4B12-9A87-913E3E6B448D', 'name': 'Natural Sounds'},
   {'id': 'A7359FC4-DAD8-45F5-AF15-7FF62F816ED3', 'name': 'Night Sky'},
   {'id': 'E06F3C94-AC8A-4B1C-A247-8EBA8910D5EE', 'name': 'Astronomy'},
   {'id': 'A155238F-0DD2-4610-9B87-05FCE1C59283',
    'name': 'River and Riparian'},
   {'id': '4244F489-6813-4B7A-9D0C-20CE098C8FFF',
    'name': 'Rock Landscapes and Features'},
   {'id': '9C9FCBB6-360B-4743-8155-6F9341CBE01B', 'name': 'Scenic Views'},
   {'id': '5BE55D7F-BDB6-4E3D-AC35-2D8EBB974417', 'name': 'Trails'},
   {'id': '78E4F4AC-AF97-435A-8C2C-7FB8D67516ED', 'name': 'Unique Species'},
   {'id': 'BA12B386-49EA-46B0-9121-FCACACC47538', 'name': 'Watersheds'},
   {'id': '5ED826E0-76BB-47BB-87DD-E081A72B0A04', 'name': 'Waterfalls'},
   {'id': '1365C347-952C-475A-B755-731DD523C195', 'name': 'Wetlands'},
   {'id': 'B85866E2-0897-4000-9040-605CA335804F', 'name': 'Wilderness'}],
  'states': 'CA',
  'contacts': {'phoneNumbers': [{'phoneNumber': '209/372-0200',
     'description': '',
     'extension': '',
     'type': 'Voice'}],
   'emailAddresses': [{'description': '',
     'emailAddress': 'yose_web_manager@nps.gov'}]},
  'entranceFees': [{'cost': '35.00',
    'description': "This fee is valid for three consecutive days for a non-commercial car, pickup truck, RV, or van with 15 or fewer passenger seats. This fee covers the vehicle and everyone inside of it. (This fee is valid for seven consecutive days when a reservation isn't required.)",
    'title': 'Entrance - Private Vehicle'},
   {'cost': '30.00',
    'description': 'This fee is valid for three consecutive days for a non-commercial motorcycle (cost is per motorcycle, not person).',
    'title': 'Entrance - Motorcycle'},
   {'cost': '20.00',
    'description': 'This fee is valid for three consecutive days for people entering on foot, a bicycle, a horse, or a non-commercial bus or van. People 15 years and younger are free.',
    'title': 'Entrance - Per Person'},
   {'cost': '25.00',
    'description': 'The fee is $25 plus $20 per person, not to exceed $105. This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Sedan'},
   {'cost': '125.00',
    'description': 'This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Van'},
   {'cost': '200.00',
    'description': 'This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Mini-bus'},
   {'cost': '300.00',
    'description': 'This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Motor Coach'},
   {'cost': '300.00',
    'description': 'The per-person fee is $20 to a maximum of $300 per vehicle. People 15 years and younger are free',
    'title': 'Entrance - Non-commercial Groups'},
   {'cost': '0.00',
    'description': 'An educational fee waiver is available for educational and scientific groups that are accredited or tax-exempt for educational purposes planning a trip for educational or scientific purposes related to Yosemite that is not primarily recreational.',
    'title': 'Entrance - Education/Academic Groups'},
   {'cost': '20.00',
    'description': 'The fee is $25 plus $20 per person, not to exceed $105. This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Per Person'},
   {'cost': '2.00',
    'description': 'A reservation will be required to drive into or through Yosemite National Park every day from 5 am to 4 pm from July 1 through August 16.',
    'title': 'Timed Entry Reservation - Park'},
   {'cost': '2.00',
    'description': 'A reservation is required to drive into or through Yosemite National Park between 5 am and 4 pm on weekends and holidays.',
    'title': 'Timed Entry Reservation - Park'}],
  'entrancePasses': [{'cost': '70.00',
    'description': 'Annual pass providing free entrance to Yosemite for 12 months from the date of purchase.',
    'title': 'Annual Entrance - Park'}],
  'fees': [],
  'directionsInfo': 'You can drive to Yosemite year-round and enter via Highways 41, 140, and 120 from the west. Tioga Pass Entrance (via Highway 120 from the east) is closed from approximately November through late May or June. Hetch Hetchy is open all year but may close intermittently due to snow. Please note that GPS units do not always provide accurate directions to or within Yosemite.',
  'directionsUrl': 'http://www.nps.gov/yose/planyourvisit/driving.htm',
  'operatingHours': [{'exceptions': [],
    'description': 'Yosemite National Park is open 24 hours per day, 365 days per year.',
    'standardHours': {'wednesday': 'All Day',
     'monday': 'All Day',
     'thursday': 'All Day',
     'sunday': 'All Day',
     'tuesday': 'All Day',
     'friday': 'All Day',
     'saturday': 'All Day'},
    'name': 'Yosemite National Park'},
   {'exceptions': [],
    'description': 'Hetch Hetchy area is only open during the day (except for permitted backpackers). All day visitors must exit Hetch Hetchy by the closure time.',
    'standardHours': {'wednesday': '7:00AM - 9:00PM',
     'monday': '7:00AM - 9:00PM',
     'thursday': '7:00AM - 9:00PM',
     'sunday': '7:00AM - 9:00PM',
     'tuesday': '7:00AM - 9:00PM',
     'friday': '7:00AM - 9:00PM',
     'saturday': '7:00AM - 9:00PM'},
    'name': 'Hetch Hetchy'}],
  'addresses': [{'postalCode': '95389',
    'city': 'Yosemite',
    'stateCode': 'CA',
    'countryCode': 'US',
    'provinceTerritoryCode': '',
    'line1': '9039 Village Drive',
    'type': 'Physical',
    'line3': '',
    'line2': ''}],
  'images': [{'credit': 'NPS Photo',
    'title': 'Upper Yosemite Fall and Merced River in spring',
    'altText': 'Upper Yosemite Fall and Merced River in spring',
    'caption': 'Upper Yosemite Fall and Merced River in spring',
    'url': 'https://www.nps.gov/common/uploads/structured_data/05383E91-AA28-2DDC-AB517507594F9FA6.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Yosemite Valley from Tunnel View',
    'altText': 'Glaciated valley with vertical cliffs.',
    'caption': 'Tunnel View is perhaps one of the most photographed views in the park.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84CAEC-1DD8-B71B-0BA0EEA50BB40F8B.jpg'},
   {'credit': 'NPS / Bob Roney',
    'title': 'Rainbow over Half Dome',
    'altText': 'A rainbow over a mountain in the distance.',
    'caption': 'A hike up to Sentinel Dome rewards people with great views of the landscape around them.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84C6CF-1DD8-B71B-0B1C7CB883AA8FB1.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Cathedral Peak and Lake in Autumn',
    'altText': 'A mountain reflecting in a lake.',
    'caption': 'Cathedral Peak is one of the most recognizable peaks in the Yosemite Wilderness.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84C3C0-1DD8-B71B-0BFF90B64283C3D8.jpg'},
   {'credit': 'NPS Photo / Cindy Jacoby',
    'title': 'Lower Yosemite Fall',
    'altText': 'A waterfall flowing down a granite cliff.',
    'caption': 'The walk to Lower Yosemite Fall is a popular and easy hike.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84CDD0-1DD8-B71B-0B6E5868AFC75B6B.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Yosemite Falls on a Winter Morning',
    'altText': 'Two tall waterfalls flowing down snow covered granite walls.',
    'caption': 'Yosemite Falls will sometimes only trickle at the end of summer, but wet winters can rejuvenate the flow.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84CC4C-1DD8-B71B-0BE967E5E5D93F25.jpg'},
   {'credit': 'NPS',
    'title': 'Glen Aulin',
    'altText': 'Mountains reflecting in water',
    'caption': 'Glen Auilin is one of five High Sierra Camps, located in the Yosemite high country.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84C82D-1DD8-B71B-0B8D6902B62369E2.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Giant Sequoia Trees in the Mariposa Grove of Giant Sequoias',
    'altText': 'Cluster of tall trees with cloudy sky.',
    'caption': "Yosemite National Park's massive giant sequoias (Sequoiadendron giganteum) live in three groves in the park. The most famous of these is the Mariposa Grove, which contains about 500 mature giant sequoias.",
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C8560E1-1DD8-B71B-0BD3183636F4B861.jpg'},
   {'credit': 'NPS',
    'title': 'Tenaya Lake at Sunset',
    'altText': 'Mountains surrounding a lake.',
    'caption': 'Tenaya Lake is a favorite place to stop along the Tioga Road in summer.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84C97E-1DD8-B71B-0B5DD2112C58C175.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Half Dome',
    'altText': 'Granite dome with trace amounts of snow.',
    'caption': 'Half Dome is one of the most recognizable granitic formations in the world.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84CF74-1DD8-B71B-0B9C7FF83F7C68EB.jpg'},
   {'credit': 'NPS Photo/ Christine Fey',
    'title': 'El Capitan',
    'altText': 'El Capitan and reflection in Merced River with some low clouds',
    'caption': 'El Capitan rises over 3,000 feet above the floor of Yosemite Valley.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/058C8410-D5BA-32F4-BC468014AF42CB0B.jpg'},
   {'credit': 'NPS Photo',
    'title': 'View of Yosemite Valley in Winter',
    'altText': 'El Capitan on left, Cathedral Rocks on the right, all covered in snow, low clouds and sun',
    'caption': 'A rewarding view of Yosemite Valley in winter as seen from Tunnel View.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/232C02DC-BE31-0C6D-E1E2D2FB1EE7E251.jpg'}],
  'weatherInfo': 'Yosemite National Park covers nearly 1,200 square miles (3,100 square km) in the Sierra Nevada, with elevations ranging from about 2,000 feet (600 m) to 13,000 ft (4,000 m). Yosemite receives 95% of its precipitation between October and May (and over 75% between November and March). Most of Yosemite is blanketed in snow from about November through May. (Yosemite Valley can be rainy or snowy in any given winter storm.)',
  'name': 'Yosemite',
  'designation': 'National Park',
  'multimedia': [],
  'relevanceScore': 1.0}]

In [150]:
lang_chat(question)

'Yosemite National Park is not just a great valley, but a shrine to human foresight, the strength of granite, the power of glaciers, the persistence of life, and the tranquility of the High Sierra. First protected in 1864, Yosemite National Park is best known for its waterfalls, but within its nearly 1,200 square miles, you can find deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area, and much more. It covers nearly 1,200 square miles in the Sierra Nevada, with elevations ranging from about 2,000 feet to 13,000 feet.'

In [151]:
gpt_chat(question)

"Yosemite National Park is located in California's Sierra Nevada mountains and is known for its stunning granite cliffs, waterfalls, giant sequoia trees, and diverse ecosystems. It is home to iconic landmarks such as El Capitan, Half Dome, and Yosemite Falls. The park offers a variety of outdoor activities including hiking, rock climbing, camping, and wildlife viewing. Yosemite is a popular destination for nature lovers and outdoor enthusiasts from around the world."

##### Location (address/state)

In [136]:
question = "Where is Yosemite"
get_context(question, model)

[{'id': '4324B2B4-D1A3-497F-8E6B-27171FAE4DB2',
  'url': 'https://www.nps.gov/yose/index.htm',
  'fullName': 'Yosemite National Park',
  'parkCode': 'yose',
  'description': 'Not just a great valley, but a shrine to human foresight, the strength of granite, the power of glaciers, the persistence of life, and the tranquility of the High Sierra. First protected in 1864, Yosemite National Park is best known for its waterfalls, but within its nearly 1,200 square miles, you can find deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area, and much more.',
  'latitude': '37.84883288',
  'longitude': '-119.5571873',
  'latLong': 'lat:37.84883288, long:-119.5571873',
  'activities': [{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42',
    'name': 'Arts and Culture'},
   {'id': '5F723BAD-7359-48FC-98FA-631592256E35', 'name': 'Auto and ATV'},
   {'id': '0B4A5320-216D-451A-9990-626E1D5ACE28', 'name': 'Scenic Driving'},
   {'id': '13A57703-BB1A-41A2-94B8-53B692EB7238', 'name': 'Astronomy'},
   {'id': '7CE6E935-F839-4FEC-A63E-052B1DEF39D2', 'name': 'Biking'},
   {'id': '071BA73C-1D3C-46D4-A53C-00D5602F7F0E', 'name': 'Boating'},
   {'id': 'A59947B7-3376-49B4-AD02-C0423E08C5F7', 'name': 'Camping'},
   {'id': '4A58AF13-E8FB-4530-B41A-97DF0B0C77B7',
    'name': 'Backcountry Camping'},
   {'id': 'B12FAAB9-713F-4B38-83E4-A273F5A43C77', 'name': 'Climbing'},
   {'id': 'AE42B46C-E4B7-4889-A122-08FE180371AE', 'name': 'Fishing'},
   {'id': '1DFACD97-1B9C-4F5A-80F2-05593604799E', 'name': 'Food'},
   {'id': 'B33DC9B6-0B7D-4322-BAD7-A13A34C584A3', 'name': 'Guided Tours'},
   {'id': '42FD78B9-2B90-4AA9-BC43-F10E9FEA8B5A', 'name': 'Hands-On'},
   {'id': 'BFF8C027-7C8F-480B-A5F8-CD8CE490BFBA', 'name': 'Hiking'},
   {'id': '7C37B79B-D02D-49EB-9020-3DB8299B748A',
    'name': 'Backcountry Hiking'},
   {'id': '0307955A-B65C-4CE4-A780-EB36BAAADF0B', 'name': 'Horse Trekking'},
   {'id': '1886DA47-0AEC-4568-B9C2-8E9BC316AAAC', 'name': 'Horseback Riding'},
   {'id': '5FF5B286-E9C3-430E-B612-3380D8138600', 'name': 'Ice Skating'},
   {'id': 'B204DE60-5A24-43DD-8902-C81625A09A74', 'name': 'Living History'},
   {'id': '4D224BCA-C127-408B-AC75-A51563C42411', 'name': 'Paddling'},
   {'id': 'DF4A35E0-7983-4A3E-BC47-F37B872B0F25',
    'name': 'Junior Ranger Program'},
   {'id': '4D06CEED-90C6-4B69-B264-32CC90B69BA6', 'name': 'Tubing'},
   {'id': '67FDB577-518E-4A3E-B608-E78941116223', 'name': 'Snow Tubing'},
   {'id': 'F9B1D433-6B86-4804-AED7-B50A519A3B7C', 'name': 'Skiing'},
   {'id': 'C38B3C62-1BBF-4EA1-A1A2-35DE21B74C17', 'name': 'Snow Play'},
   {'id': '01D717BC-18BB-4FE4-95BA-6B13AD702038', 'name': 'Snowshoeing'},
   {'id': '587BB2D3-EC35-41B2-B3F7-A39E2B088AEE', 'name': 'Swimming'},
   {'id': '0B685688-3405-4E2A-ABBA-E3069492EC50', 'name': 'Wildlife Watching'},
   {'id': '5A2C91D1-50EC-4B24-8BED-A2E11A1892DF', 'name': 'Birdwatching'},
   {'id': '0C0D142F-06B5-4BE1-8B44-491B90F93DEB', 'name': 'Park Film'},
   {'id': 'C8F98B28-3C10-41AE-AA99-092B3B398C43', 'name': 'Museum Exhibits'},
   {'id': '24380E3F-AD9D-4E38-BF13-C8EEB21893E7', 'name': 'Shopping'},
   {'id': '467DC8B8-0B7D-436D-A026-80A22358F615',
    'name': 'Bookstore and Park Store'}],
  'topics': [{'id': '69693007-2DF2-4EDE-BB3B-A25EBA72BDF5',
    'name': 'Architecture and Building'},
   {'id': '28AEAE85-9DDA-45B6-981B-1CFCDCC61E14',
    'name': 'African American Heritage'},
   {'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B', 'name': 'Archeology'},
   {'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370', 'name': 'Arts'},
   {'id': '05B7868A-3F3C-433D-876E-A886C4BE7A12', 'name': 'Painting'},
   {'id': '9BD60DC0-C82B-42BA-A170-456B7423429D', 'name': 'Photography'},
   {'id': '227D2677-28CA-4CBF-997F-61108975A497',
    'name': 'Asian American Heritage'},
   {'id': '607D41B0-F830-4C07-A557-BCEF880A3929',
    'name': 'Burial, Cemetery and Gravesite'},
   {'id': 'A1BAF33E-EA84-4608-A888-4CEE9541F027',
    'name': 'Native American Heritage'},
   {'id': '518B32FB-339D-4C52-B2C2-04BF406AA4B0',
    'name': 'Religion and Spirituality'},
   {'id': '98F41FDF-B73F-4B68-8010-53CCB2891E3B', 'name': 'Churches'},
   {'id': '3CDB67A9-1EAC-408D-88EC-F26FA35E90AF',
    'name': 'Schools and Education'},
   {'id': 'D1CF31DE-AFED-412B-9425-DD1FD4CBB5C7',
    'name': 'Science, Technology and Innovation'},
   {'id': 'FE2C2613-B41E-4531-BC43-03EB6E45CBCF', 'name': 'Transportation'},
   {'id': 'A160B3D9-1603-4D89-B82F-21FCAF9EEE3B', 'name': 'Tragic Events'},
   {'id': 'D91B6F1A-FED8-490D-B181-9940474CD67C', 'name': 'Floods'},
   {'id': '7DA81DAB-5045-4953-9C20-36590AD9FA95', 'name': "Women's History"},
   {'id': '0D00073E-18C3-46E5-8727-2F87B112DDC6', 'name': 'Animals'},
   {'id': '957EF2BD-AC6C-4B7B-BD9A-87593ADC6691', 'name': 'Birds'},
   {'id': '2539614A-9646-446E-8251-34D3AAE068FA', 'name': 'Cats (wild)'},
   {'id': '1608649A-E7D7-4529-BD83-074C90F9FB68', 'name': 'Fish'},
   {'id': '4DC11D06-00F1-4A01-81D0-89CCCCE4FF50', 'name': 'Climate Change'},
   {'id': '04A39AB8-DD02-432F-AE5F-BA1267D41A0D', 'name': 'Fire'},
   {'id': '9F6A7003-59D6-4438-935F-760FD04C1073',
    'name': 'Foothills, Plains and Valleys'},
   {'id': '41B1A0A3-11FF-4F55-9CB9-034A7E28B087',
    'name': 'Forests and Woodlands'},
   {'id': 'F0F97E32-2F29-41B4-AF98-9FBE8DAB36B1', 'name': 'Geology'},
   {'id': 'FBB14C45-1663-4714-9D28-B2B99874644D', 'name': 'Glaciers'},
   {'id': '94262026-92F5-48E9-90EF-01CEAEFBA4FF', 'name': 'Grasslands'},
   {'id': 'AEA4C5FD-F25C-4C3D-97FE-2767ED3EE682', 'name': 'Meadows'},
   {'id': '1CF1F6BB-A037-445B-8CF2-81428E50CE52', 'name': 'Lakes'},
   {'id': '101F4D51-F99D-45A6-BBB6-CD481E5FACED', 'name': 'Mountains'},
   {'id': 'F8C2FE93-DEB3-4B12-9A87-913E3E6B448D', 'name': 'Natural Sounds'},
   {'id': 'A7359FC4-DAD8-45F5-AF15-7FF62F816ED3', 'name': 'Night Sky'},
   {'id': 'E06F3C94-AC8A-4B1C-A247-8EBA8910D5EE', 'name': 'Astronomy'},
   {'id': 'A155238F-0DD2-4610-9B87-05FCE1C59283',
    'name': 'River and Riparian'},
   {'id': '4244F489-6813-4B7A-9D0C-20CE098C8FFF',
    'name': 'Rock Landscapes and Features'},
   {'id': '9C9FCBB6-360B-4743-8155-6F9341CBE01B', 'name': 'Scenic Views'},
   {'id': '5BE55D7F-BDB6-4E3D-AC35-2D8EBB974417', 'name': 'Trails'},
   {'id': '78E4F4AC-AF97-435A-8C2C-7FB8D67516ED', 'name': 'Unique Species'},
   {'id': 'BA12B386-49EA-46B0-9121-FCACACC47538', 'name': 'Watersheds'},
   {'id': '5ED826E0-76BB-47BB-87DD-E081A72B0A04', 'name': 'Waterfalls'},
   {'id': '1365C347-952C-475A-B755-731DD523C195', 'name': 'Wetlands'},
   {'id': 'B85866E2-0897-4000-9040-605CA335804F', 'name': 'Wilderness'}],
  'states': 'CA',
  'contacts': {'phoneNumbers': [{'phoneNumber': '209/372-0200',
     'description': '',
     'extension': '',
     'type': 'Voice'}],
   'emailAddresses': [{'description': '',
     'emailAddress': 'yose_web_manager@nps.gov'}]},
  'entranceFees': [{'cost': '35.00',
    'description': "This fee is valid for three consecutive days for a non-commercial car, pickup truck, RV, or van with 15 or fewer passenger seats. This fee covers the vehicle and everyone inside of it. (This fee is valid for seven consecutive days when a reservation isn't required.)",
    'title': 'Entrance - Private Vehicle'},
   {'cost': '30.00',
    'description': 'This fee is valid for three consecutive days for a non-commercial motorcycle (cost is per motorcycle, not person).',
    'title': 'Entrance - Motorcycle'},
   {'cost': '20.00',
    'description': 'This fee is valid for three consecutive days for people entering on foot, a bicycle, a horse, or a non-commercial bus or van. People 15 years and younger are free.',
    'title': 'Entrance - Per Person'},
   {'cost': '25.00',
    'description': 'The fee is $25 plus $20 per person, not to exceed $105. This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Sedan'},
   {'cost': '125.00',
    'description': 'This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Van'},
   {'cost': '200.00',
    'description': 'This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Mini-bus'},
   {'cost': '300.00',
    'description': 'This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Motor Coach'},
   {'cost': '300.00',
    'description': 'The per-person fee is $20 to a maximum of $300 per vehicle. People 15 years and younger are free',
    'title': 'Entrance - Non-commercial Groups'},
   {'cost': '0.00',
    'description': 'An educational fee waiver is available for educational and scientific groups that are accredited or tax-exempt for educational purposes planning a trip for educational or scientific purposes related to Yosemite that is not primarily recreational.',
    'title': 'Entrance - Education/Academic Groups'},
   {'cost': '20.00',
    'description': 'The fee is $25 plus $20 per person, not to exceed $105. This fee is valid for seven consecutive days. A commercial use authorization is required.',
    'title': 'Commercial Entrance - Per Person'},
   {'cost': '2.00',
    'description': 'A reservation will be required to drive into or through Yosemite National Park every day from 5 am to 4 pm from July 1 through August 16.',
    'title': 'Timed Entry Reservation - Park'},
   {'cost': '2.00',
    'description': 'A reservation is required to drive into or through Yosemite National Park between 5 am and 4 pm on weekends and holidays.',
    'title': 'Timed Entry Reservation - Park'}],
  'entrancePasses': [{'cost': '70.00',
    'description': 'Annual pass providing free entrance to Yosemite for 12 months from the date of purchase.',
    'title': 'Annual Entrance - Park'}],
  'fees': [],
  'directionsInfo': 'You can drive to Yosemite year-round and enter via Highways 41, 140, and 120 from the west. Tioga Pass Entrance (via Highway 120 from the east) is closed from approximately November through late May or June. Hetch Hetchy is open all year but may close intermittently due to snow. Please note that GPS units do not always provide accurate directions to or within Yosemite.',
  'directionsUrl': 'http://www.nps.gov/yose/planyourvisit/driving.htm',
  'operatingHours': [{'exceptions': [],
    'description': 'Yosemite National Park is open 24 hours per day, 365 days per year.',
    'standardHours': {'wednesday': 'All Day',
     'monday': 'All Day',
     'thursday': 'All Day',
     'sunday': 'All Day',
     'tuesday': 'All Day',
     'friday': 'All Day',
     'saturday': 'All Day'},
    'name': 'Yosemite National Park'},
   {'exceptions': [],
    'description': 'Hetch Hetchy area is only open during the day (except for permitted backpackers). All day visitors must exit Hetch Hetchy by the closure time.',
    'standardHours': {'wednesday': '7:00AM - 9:00PM',
     'monday': '7:00AM - 9:00PM',
     'thursday': '7:00AM - 9:00PM',
     'sunday': '7:00AM - 9:00PM',
     'tuesday': '7:00AM - 9:00PM',
     'friday': '7:00AM - 9:00PM',
     'saturday': '7:00AM - 9:00PM'},
    'name': 'Hetch Hetchy'}],
  'addresses': [{'postalCode': '95389',
    'city': 'Yosemite',
    'stateCode': 'CA',
    'countryCode': 'US',
    'provinceTerritoryCode': '',
    'line1': '9039 Village Drive',
    'type': 'Physical',
    'line3': '',
    'line2': ''}],
  'images': [{'credit': 'NPS Photo',
    'title': 'Upper Yosemite Fall and Merced River in spring',
    'altText': 'Upper Yosemite Fall and Merced River in spring',
    'caption': 'Upper Yosemite Fall and Merced River in spring',
    'url': 'https://www.nps.gov/common/uploads/structured_data/05383E91-AA28-2DDC-AB517507594F9FA6.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Yosemite Valley from Tunnel View',
    'altText': 'Glaciated valley with vertical cliffs.',
    'caption': 'Tunnel View is perhaps one of the most photographed views in the park.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84CAEC-1DD8-B71B-0BA0EEA50BB40F8B.jpg'},
   {'credit': 'NPS / Bob Roney',
    'title': 'Rainbow over Half Dome',
    'altText': 'A rainbow over a mountain in the distance.',
    'caption': 'A hike up to Sentinel Dome rewards people with great views of the landscape around them.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84C6CF-1DD8-B71B-0B1C7CB883AA8FB1.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Cathedral Peak and Lake in Autumn',
    'altText': 'A mountain reflecting in a lake.',
    'caption': 'Cathedral Peak is one of the most recognizable peaks in the Yosemite Wilderness.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84C3C0-1DD8-B71B-0BFF90B64283C3D8.jpg'},
   {'credit': 'NPS Photo / Cindy Jacoby',
    'title': 'Lower Yosemite Fall',
    'altText': 'A waterfall flowing down a granite cliff.',
    'caption': 'The walk to Lower Yosemite Fall is a popular and easy hike.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84CDD0-1DD8-B71B-0B6E5868AFC75B6B.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Yosemite Falls on a Winter Morning',
    'altText': 'Two tall waterfalls flowing down snow covered granite walls.',
    'caption': 'Yosemite Falls will sometimes only trickle at the end of summer, but wet winters can rejuvenate the flow.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84CC4C-1DD8-B71B-0BE967E5E5D93F25.jpg'},
   {'credit': 'NPS',
    'title': 'Glen Aulin',
    'altText': 'Mountains reflecting in water',
    'caption': 'Glen Auilin is one of five High Sierra Camps, located in the Yosemite high country.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84C82D-1DD8-B71B-0B8D6902B62369E2.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Giant Sequoia Trees in the Mariposa Grove of Giant Sequoias',
    'altText': 'Cluster of tall trees with cloudy sky.',
    'caption': "Yosemite National Park's massive giant sequoias (Sequoiadendron giganteum) live in three groves in the park. The most famous of these is the Mariposa Grove, which contains about 500 mature giant sequoias.",
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C8560E1-1DD8-B71B-0BD3183636F4B861.jpg'},
   {'credit': 'NPS',
    'title': 'Tenaya Lake at Sunset',
    'altText': 'Mountains surrounding a lake.',
    'caption': 'Tenaya Lake is a favorite place to stop along the Tioga Road in summer.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84C97E-1DD8-B71B-0B5DD2112C58C175.jpg'},
   {'credit': 'NPS / Cindy Jacoby',
    'title': 'Half Dome',
    'altText': 'Granite dome with trace amounts of snow.',
    'caption': 'Half Dome is one of the most recognizable granitic formations in the world.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C84CF74-1DD8-B71B-0B9C7FF83F7C68EB.jpg'},
   {'credit': 'NPS Photo/ Christine Fey',
    'title': 'El Capitan',
    'altText': 'El Capitan and reflection in Merced River with some low clouds',
    'caption': 'El Capitan rises over 3,000 feet above the floor of Yosemite Valley.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/058C8410-D5BA-32F4-BC468014AF42CB0B.jpg'},
   {'credit': 'NPS Photo',
    'title': 'View of Yosemite Valley in Winter',
    'altText': 'El Capitan on left, Cathedral Rocks on the right, all covered in snow, low clouds and sun',
    'caption': 'A rewarding view of Yosemite Valley in winter as seen from Tunnel View.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/232C02DC-BE31-0C6D-E1E2D2FB1EE7E251.jpg'}],
  'weatherInfo': 'Yosemite National Park covers nearly 1,200 square miles (3,100 square km) in the Sierra Nevada, with elevations ranging from about 2,000 feet (600 m) to 13,000 ft (4,000 m). Yosemite receives 95% of its precipitation between October and May (and over 75% between November and March). Most of Yosemite is blanketed in snow from about November through May. (Yosemite Valley can be rainy or snowy in any given winter storm.)',
  'name': 'Yosemite',
  'designation': 'National Park',
  'multimedia': [],
  'relevanceScore': 1.0}]

In [137]:
lang_chat(question)

'Yosemite National Park is located in California.'

In [138]:
gpt_chat(question)

'Yosemite National Park is located in California, USA. It covers an area of over 750,000 acres in the Sierra Nevada mountains.'

#### Events

In [139]:
question = "What events are at Yosemite"
get_context(question, model)

[{'location': 'Glacier Point is located about 30 miles (48 km) or 1 hour from Yosemite Valley.',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Talk', 'Walk'],
  'createuser': '',
  'isfree': 'true',
  'contactemailaddress': '',
  'regresurl': '',
  'description': '<p>Acompaña a un guardaparques a aprender sobre Yosemite en Glacier Point. Domingo y miércoles, 2 pm a 3 pm.</p>',
  'images': [{'path': '/common/uploads/event_calendar/A89D7D8B-F4D7-CD65-04894ADDA6E8EFC5.jpg',
    'credit': 'NPS',
    'imageId': '43904',
    'altText': 'Arrowhead symbol for the National Park Service.',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by the National Park Service',
    'url': '/common/uploads/event_calendar/A89D7D8B-F4D7-CD65-04894ADDA6E8EFC5.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'false',
  'organizationname': '',
  'id': 'A8AF69CB-9906-162A-AA3F2A01AF1429E7',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': '',
  'times': [{'timestart': '02:00 PM',
    'timeend': '03:00 PM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'No',
  'timeinfo': '',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-07-17',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'This is a free program.',
  'recurrencerule': 'DTSTART=20240717T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=SU,WE;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07', '2024-08-11', '2024-08-14', '2024-08-18'],
  'datetimecreated': '',
  'title': '¡En español! Programa de Guardaparques (Glacier Point)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': 'Classes meet at the Happy Isles Art and Nature Center in Yosemite Valley (shuttle stop 16.)',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Partner Program'],
  'createuser': '',
  'isfree': 'false',
  'contactemailaddress': '',
  'regresurl': 'https://yosemite.org/experience/art/',
  'description': '<p>Join a guest instructor (all professional artists) for a hands-on, four-hour outdoor art workshop in Yosemite Valley. Meets at the Happy Isles Art &amp; Nature Center. Check Yosemite.org/art for class schedule and registration.</p>',
  'images': [{'path': '/common/uploads/event_calendar/EF1BEA80-05DD-5295-D70134291FDEFE2A.jpg',
    'credit': 'YC',
    'imageId': '42903',
    'altText': 'Logo for Yosemite Conservancy',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by Yosemite Conservancy',
    'url': '/common/uploads/event_calendar/EF1BEA80-05DD-5295-D70134291FDEFE2A.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'true',
  'organizationname': '',
  'id': 'EF22DAA9-9957-7027-9605BCF5CF55DDAB',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': 'https://yosemite.org/experience/art/',
  'times': [{'timestart': '09:00 AM',
    'timeend': '01:00 PM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'Visit the Yosemite Conservancy website for class schedule and registration.',
  'timeinfo': '',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-05-08',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'Check the Yosemite Conservancy website for class schedule and pricing.',
  'recurrencerule': 'DTSTART=20240508T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=MO,TU,WE,TH,FR;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07',
   '2024-08-08',
   '2024-08-09',
   '2024-08-12',
   '2024-08-13',
   '2024-08-14',
   '2024-08-15',
   '2024-08-16',
   '2024-08-19',
   '2024-08-20'],
  'datetimecreated': '',
  'title': 'Art Class (Yosemite Valley)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': 'Tuolumne Meadows is located about 1.5 hours from Yosemite Valley, near the Tioga Pass Entrance.',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Walk'],
  'createuser': '',
  'isfree': 'true',
  'contactemailaddress': '',
  'regresurl': '',
  'description': '<p>Bird Walk with a Tuolumne Meadows expert. Easy stroll. Binoculars available. Meet at Lembert Dome Parking.</p>',
  'images': [{'path': '/common/uploads/event_calendar/218596E1-E09A-1ED4-F23A06BA47F37187.jpg',
    'credit': 'NPS',
    'imageId': '43573',
    'altText': 'Arrowhead symbol for the National Park Service.',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by the National Park Service',
    'url': '/common/uploads/event_calendar/218596E1-E09A-1ED4-F23A06BA47F37187.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'false',
  'organizationname': '',
  'id': '218D3081-A654-934D-D665B1A65D1595EA',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': '',
  'times': [{'timestart': '07:30 AM',
    'timeend': '10:00 AM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'Drop-in only.',
  'timeinfo': '',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-06-12',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'This is a free program.',
  'recurrencerule': 'DTSTART=20240612T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=WE,SA;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07', '2024-08-10', '2024-08-14', '2024-08-17'],
  'datetimecreated': '',
  'title': 'Bird Walk (Tuolumne Meadows)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': 'Wawona Campground is located about one hour from Yosemite Valley.',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Campfire/Evening Program'],
  'createuser': '',
  'isfree': 'true',
  'contactemailaddress': '',
  'regresurl': '',
  'description': '<p>Meet at Wawona campground amphitheater.</p>',
  'images': [{'path': '/common/uploads/event_calendar/211DC431-BCBB-79DA-84901E8BD0DBDBE4.jpg',
    'credit': 'NPS',
    'imageId': '43571',
    'altText': 'Arrowhead symbol for the National Park Service.',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by the National Park Service',
    'url': '/common/uploads/event_calendar/211DC431-BCBB-79DA-84901E8BD0DBDBE4.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'false',
  'organizationname': '',
  'id': '2123D146-0935-ED99-AF7503C6AD0FCA64',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': '',
  'times': [{'timestart': '07:00 PM',
    'timeend': '08:00 PM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'Drop-in only.',
  'timeinfo': '',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-06-12',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'This is a free program.',
  'recurrencerule': 'DTSTART=20240612T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=WE,SA;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07', '2024-08-10', '2024-08-14', '2024-08-17'],
  'datetimecreated': '',
  'title': 'Campfire Program (Wawona)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': 'Tuolumne Meadows is located about 1.5 hours from Yosemite Valley, near the Tioga Pass Entrance.',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Campfire/Evening Program'],
  'createuser': '',
  'isfree': 'true',
  'contactemailaddress': '',
  'regresurl': '',
  'description': '<p>Share stories of your days in Tuolumne Meadows with a park ranger around the campfire. Meets at Tuolumne Meadows Lodge.</p>\n<p>------</p>\n<h4>Evening Programs in Tuolumne Meadows</h4>\n<p>July 17 - Campfireside Chat<br />July 18 - The Uncommonly Brilliant Raven<br />July 19 - A Land of Sound: Cultural Histories and Folk Music<br />July 20 - Pellets, Parliaments, and Protection: Yosemite’s Owls<br />July 21 - Campfireside Chat<br />July 22 - The Perfect Fire<br />July 23 - Opening to Change<br />July 24 - Campfireside Chat<br />July 25 - Up Late with Nocturnal Animals<br />July 26 - Hidden Treasure of the Meadows<br />July 27 - A Land of Sound: Cultural Histories and Folk Music<br />July 28 - Campfireside Chat<br />July 29 - The Perfect Fire<br />July 30 - Pellets, Parliaments, and Protection: Yosemite’s Owls<br />July 31 - Campfireside Chat<br />August - Programs TBD</p>',
  'images': [{'path': '/common/uploads/event_calendar/218596E1-E09A-1ED4-F23A06BA47F37187.jpg',
    'credit': 'NPS',
    'imageId': '43573',
    'altText': 'Arrowhead symbol for the National Park Service.',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by the National Park Service',
    'url': '/common/uploads/event_calendar/218596E1-E09A-1ED4-F23A06BA47F37187.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'false',
  'organizationname': '',
  'id': 'C1A9726D-D764-248E-DC735BEA2E9C7F7F',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': '',
  'times': [{'timestart': '08:00 PM',
    'timeend': '08:45 PM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'Drop-in only.',
  'timeinfo': '',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-07-17',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'This is a free program.',
  'recurrencerule': 'DTSTART=20240717T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=SU,WE;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07', '2024-08-11', '2024-08-14', '2024-08-18'],
  'datetimecreated': '',
  'title': 'Campfireside Chat with a Ranger (Tuolumne Meadows)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': 'Located at Pine Tree Market in Wawona, about one hour south of Yosemite Valley. From Wawona Road, turn onto Chilnualna Falls Rd and drive about one mile to the market.',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Talk'],
  'createuser': '',
  'isfree': 'true',
  'contactemailaddress': '',
  'regresurl': '',
  'description': '<p>Meet at Pine Tree Market for coffee, a Q&amp;A session, and general park updates with a ranger. Drop-ins welcome!</p>',
  'images': [{'path': '/common/uploads/event_calendar/F217FF38-FBE7-10FF-D907A44A7D3B697D.jpg',
    'credit': 'NPS',
    'imageId': '42904',
    'altText': 'Arrowhead symbol for the National Park Service.',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by the National Park Service',
    'url': '/common/uploads/event_calendar/F217FF38-FBE7-10FF-D907A44A7D3B697D.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'false',
  'organizationname': '',
  'id': 'F2202583-9B80-7629-E9112B1B72B0ADA4',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': '',
  'times': [{'timestart': '09:00 AM',
    'timeend': '10:00 AM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'Drop-in only.',
  'timeinfo': 'Stop by anytime between 9 and 10 am!',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-05-08',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'This is a free program.',
  'recurrencerule': 'DTSTART=20240508T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=SU,WE;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07', '2024-08-11', '2024-08-14', '2024-08-18'],
  'datetimecreated': '',
  'title': 'Coffee With a Ranger (Wawona)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': 'Meet at the Curry Village Amphitheater (Shuttle stops 14 & 19.)',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Guided Tour', 'Partner Program'],
  'createuser': '',
  'isfree': 'true',
  'contactemailaddress': '',
  'regresurl': '',
  'description': '<p>Explore the exciting history of the Curry Village Historic District on this hour-long guided tour. Meet at the Curry Village Amphitheater (Shuttle stops 14 &amp; 19.)</p>',
  'images': [{'path': '/common/uploads/event_calendar/E77080EC-F9CC-DD17-9E5CE3872EF52CAB.jpg',
    'credit': 'YH',
    'imageId': '42889',
    'altText': 'Logo for Yosemite Hospitality',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by Yosemite Hospitality.',
    'url': '/common/uploads/event_calendar/E77080EC-F9CC-DD17-9E5CE3872EF52CAB.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'false',
  'organizationname': '',
  'id': 'E7876A16-AA90-0469-7E54ED416692C182',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': '',
  'times': [{'timestart': '03:00 PM',
    'timeend': '04:00 PM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'Drop-in only.',
  'timeinfo': '',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-05-08',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'This is a free tour.',
  'recurrencerule': 'DTSTART=20240508T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=SU,MO,TU,WE,TH,FR,SA;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07',
   '2024-08-08',
   '2024-08-09',
   '2024-08-10',
   '2024-08-11',
   '2024-08-12',
   '2024-08-13',
   '2024-08-14',
   '2024-08-15',
   '2024-08-16',
   '2024-08-17',
   '2024-08-18',
   '2024-08-19',
   '2024-08-20'],
  'datetimecreated': '',
  'title': 'Curry Village Historic Tour (Yosemite Valley)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': '',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Hike', 'Partner Program'],
  'createuser': '',
  'isfree': 'false',
  'contactemailaddress': '',
  'regresurl': 'https://www.travelyosemite.com/things-to-do/hiking/guided-group-hikes/',
  'description': '<p>Join the Yosemite Mountaineering School for a guided group hike in Yosemite Valley!</p>\n<p>Half-day and full-day group hikes are offered from May through October for hikers of all experience levels. Bring a small backpack with at least 2 liters of water (some situations require more), snacks, lunch, hat, sunglasses, sunscreen and extra layers.</p>\n<p>Check the website for details and to book your spot!</p>\n<p><em>All hikers must be at least 12 years old.</em></p>',
  'images': [{'path': '/common/uploads/event_calendar/C2AA717E-0312-E12B-9A81F5CDCAA7F1F5.jpg',
    'credit': 'YH',
    'imageId': '43918',
    'altText': 'Logo for Yosemite Hospitality',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by Yosemite Hospitality.',
    'url': '/common/uploads/event_calendar/C2AA717E-0312-E12B-9A81F5CDCAA7F1F5.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'true',
  'organizationname': '',
  'id': 'C2BC81A8-D17D-EE20-7EE9126683A51D8C',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': 'https://www.travelyosemite.com/things-to-do/hiking/guided-group-hikes/',
  'times': [{'timestart': '08:30 AM',
    'timeend': '12:30 PM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'Book online or at an in-park tour and activity kiosk.',
  'timeinfo': '',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-07-17',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'Check the website for pricing.',
  'recurrencerule': 'DTSTART=20240717T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=MO,WE,SA;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07',
   '2024-08-10',
   '2024-08-12',
   '2024-08-14',
   '2024-08-17',
   '2024-08-19'],
  'datetimecreated': '',
  'title': 'Discovery Hike: Vernal Fall Footbridge (Yosemite Valley)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': '',
  'updateuser': '',
  'contactname': '',
  'contacttelephonenumber': '',
  'recurrencedateend': '2024-08-20',
  'longitude': '',
  'datestart': '2024-08-07',
  'isrecurring': 'true',
  'datetimeupdated': '',
  'portalname': '',
  'types': ['Hike', 'Partner Program'],
  'createuser': '',
  'isfree': 'false',
  'contactemailaddress': '',
  'regresurl': 'https://www.travelyosemite.com/things-to-do/hiking/guided-group-hikes/',
  'description': '<p>Join the Yosemite Mountaineering School for a guided group hike in Yosemite Valley!</p>\n<p>Half-day and full-day group hikes are offered from May through October for hikers of all experience levels. Bring a small backpack with at least 2 liters of water (some situations require more), snacks, lunch, hat, sunglasses, sunscreen and extra layers.</p>\n<p>Check the website for details and to book your spot!</p>\n<p><em>All hikers must be at least 12 years old.</em></p>',
  'images': [{'path': '/common/uploads/event_calendar/C2AA717E-0312-E12B-9A81F5CDCAA7F1F5.jpg',
    'credit': 'YH',
    'imageId': '43918',
    'altText': 'Logo for Yosemite Hospitality',
    'title': '',
    'ordinal': '0',
    'caption': 'This program is hosted by Yosemite Hospitality.',
    'url': '/common/uploads/event_calendar/C2AA717E-0312-E12B-9A81F5CDCAA7F1F5.jpg'}],
  'category': 'Regular Event',
  'imageidlist': '',
  'isregresrequired': 'true',
  'organizationname': '',
  'id': 'C2C22FF8-DAA0-CA84-0E1B4757BF677EB5',
  'isallday': 'false',
  'dateend': '2024-08-07',
  'sitecode': 'yose',
  'infourl': 'https://www.travelyosemite.com/things-to-do/hiking/guided-group-hikes/',
  'times': [{'timestart': '01:30 PM',
    'timeend': '05:30 PM',
    'sunsetend': 'false',
    'sunrisestart': 'false'}],
  'regresinfo': 'Book online or at an in-park tour and activity kiosk.',
  'timeinfo': '',
  'categoryid': '0',
  'eventid': '0',
  'parkfullname': 'Yosemite National Park',
  'recurrencedatestart': '2024-07-17',
  'date': '2024-08-07',
  'sitetype': 'park',
  'feeinfo': 'Check the website for pricing.',
  'recurrencerule': 'DTSTART=20240717T070000Z;UNTIL=20240820T070000Z;FREQ=WEEKLY;WKST=SU;BYDAY=MO,WE,SA;COUNT=0;INTERVAL=1',
  'dates': ['2024-08-07',
   '2024-08-10',
   '2024-08-12',
   '2024-08-14',
   '2024-08-17',
   '2024-08-19'],
  'datetimecreated': '',
  'title': 'Discovery Hike: Vernal Fall Footbridge (Yosemite Valley)',
  'latitude': '',
  'subjectname': '',
  'tags': []},
 {'location': 'Tuolumne Meadows is located about 1.5 hours from Yosemite Valley, near the Tioga Pass Entrance.',
  'updateuser': '',

In [140]:
lang_chat(question)

'Here are some events happening at Yosemite National Park:\n\n1. ¡En español! Programa de Guardaparques (Glacier Point)\n2. Art Class (Yosemite Valley)\n3. Bird Walk (Tuolumne Meadows)\n4. Campfire Program (Wawona)\n5. Campfireside Chat with a Ranger (Tuolumne Meadows)\n6. Coffee With a Ranger (Wawona)\n7. Curry Village Historic Tour (Yosemite Valley)\n8. Discovery Hike: Vernal Fall Footbridge (Yosemite Valley)\n9. Dog Lake Hike with a Ranger (Tuolumne Meadows)'

In [142]:
gpt_chat(question)

'Yosemite National Park in California offers a variety of events throughout the year, including guided hikes, photography workshops, stargazing programs, art classes, and ranger-led talks. You can check the official Yosemite National Park website or contact the park directly for the most up-to-date information on events and activities.'

#### Address

In [143]:
question = "What is address of everglades"
get_context(question, model)

[{'id': '5EA02193-276A-4037-B7DB-5765A56935FD',
  'url': 'https://www.nps.gov/ever/index.htm',
  'fullName': 'Everglades National Park',
  'parkCode': 'ever',
  'description': 'Everglades National Park protects an unparalleled landscape that provides important habitat for numerous rare and endangered species like the manatee, American crocodile, and the elusive Florida panther. An international treasure as well - a World Heritage Site, International Biosphere Reserve, a Wetland of International Importance, and a specially protected area under the Cartagena Treaty.',
  'latitude': '25.37294225',
  'longitude': '-80.88200301',
  'latLong': 'lat:25.37294225, long:-80.88200301',
  'activities': [{'id': '5F723BAD-7359-48FC-98FA-631592256E35',
    'name': 'Auto and ATV'},
   {'id': '0B4A5320-216D-451A-9990-626E1D5ACE28', 'name': 'Scenic Driving'},
   {'id': '13A57703-BB1A-41A2-94B8-53B692EB7238', 'name': 'Astronomy'},
   {'id': 'D37A0003-8317-4F04-8FB0-4CF0A272E195', 'name': 'Stargazing'},
   {'id': '7CE6E935-F839-4FEC-A63E-052B1DEF39D2', 'name': 'Biking'},
   {'id': '8D778629-F603-4C50-A121-6F4BB2FE2C4B', 'name': 'Road Biking'},
   {'id': '071BA73C-1D3C-46D4-A53C-00D5602F7F0E', 'name': 'Boating'},
   {'id': 'E0E4CE55-3119-46DE-86EB-6817CD8D5F30', 'name': 'Motorized Boating'},
   {'id': 'BB0B8CD0-BF4C-4517-9980-CFE2D149C7B4', 'name': 'Sailing'},
   {'id': 'A510F02B-8938-4679-A4F9-76580BCAE9C7', 'name': 'Boat Tour'},
   {'id': 'A59947B7-3376-49B4-AD02-C0423E08C5F7', 'name': 'Camping'},
   {'id': '4A58AF13-E8FB-4530-B41A-97DF0B0C77B7',
    'name': 'Backcountry Camping'},
   {'id': '907E8125-15E4-483C-8EAD-B9FA1E85C6F8',
    'name': 'Canoe or Kayak Camping'},
   {'id': '9159DF0F-951D-4AAE-9987-CEB3CE2A9ADA',
    'name': 'Car or Front Country Camping'},
   {'id': '7CFF5F03-5ECC-4F5A-8572-75D1F0976C0C', 'name': 'Group Camping'},
   {'id': 'C5C5971C-E325-4CEB-8C81-EE49A881DF17', 'name': 'RV Camping'},
   {'id': 'C11D3746-5063-4BD0-B245-7178D1AD866C', 'name': 'Compass and GPS'},
   {'id': 'CA3641A0-FADC-497F-B036-3FE426D0DDCC', 'name': 'Geocaching'},
   {'id': 'AE42B46C-E4B7-4889-A122-08FE180371AE', 'name': 'Fishing'},
   {'id': '25FB188F-5AAD-459A-9092-28A9801709FF',
    'name': 'Freshwater Fishing'},
   {'id': '17411C8D-5769-4D0F-ABD1-52ED03840C18', 'name': 'Saltwater Fishing'},
   {'id': '1DFACD97-1B9C-4F5A-80F2-05593604799E', 'name': 'Food'},
   {'id': 'C6D3230A-2CEA-4AFE-BFF3-DC1E2C2C4BB4', 'name': 'Picnicking'},
   {'id': 'B33DC9B6-0B7D-4322-BAD7-A13A34C584A3', 'name': 'Guided Tours'},
   {'id': 'A0631906-9672-4583-91DE-113B93DB6B6E',
    'name': 'Self-Guided Tours - Walking'},
   {'id': 'C7D5A145-F8EB-4C37-9E92-2F6C6206B196',
    'name': 'Self-Guided Tours - Auto'},
   {'id': '3DE599E2-22ED-40BF-B383-EDA073563C1E',
    'name': 'Bus/Shuttle Guided Tour'},
   {'id': '5A241412-0CFB-497A-9B5F-0AB8C03CDE72', 'name': 'Boat Tour'},
   {'id': '42FD78B9-2B90-4AA9-BC43-F10E9FEA8B5A', 'name': 'Hands-On'},
   {'id': '31F88DA6-696F-441F-89CF-D7B1415C4CB9', 'name': 'Citizen Science'},
   {'id': '9456A40A-AF75-4AD3-8BE1-79C4A7DBEDFC',
    'name': 'Volunteer Vacation'},
   {'id': 'BFF8C027-7C8F-480B-A5F8-CD8CE490BFBA', 'name': 'Hiking'},
   {'id': '7C37B79B-D02D-49EB-9020-3DB8299B748A',
    'name': 'Backcountry Hiking'},
   {'id': '45261C0A-00D8-4C27-A1F8-029F933A0D34',
    'name': 'Front-Country Hiking'},
   {'id': '4D224BCA-C127-408B-AC75-A51563C42411', 'name': 'Paddling'},
   {'id': '21DB3AFC-8AAC-4665-BC1F-7198C0685983', 'name': 'Canoeing'},
   {'id': '256543C7-4322-48B3-8978-765E89AA9431',
    'name': 'Canoe or Kayak Camping'},
   {'id': 'F353A9ED-4A08-456E-8DEC-E61974D0FEB6', 'name': 'Kayaking'},
   {'id': 'DF4A35E0-7983-4A3E-BC47-F37B872B0F25',
    'name': 'Junior Ranger Program'},
   {'id': '0B685688-3405-4E2A-ABBA-E3069492EC50', 'name': 'Wildlife Watching'},
   {'id': '5A2C91D1-50EC-4B24-8BED-A2E11A1892DF', 'name': 'Birdwatching'},
   {'id': '0C0D142F-06B5-4BE1-8B44-491B90F93DEB', 'name': 'Park Film'},
   {'id': 'C8F98B28-3C10-41AE-AA99-092B3B398C43', 'name': 'Museum Exhibits'},
   {'id': '24380E3F-AD9D-4E38-BF13-C8EEB21893E7', 'name': 'Shopping'},
   {'id': '467DC8B8-0B7D-436D-A026-80A22358F615',
    'name': 'Bookstore and Park Store'},
   {'id': '43800AD1-D439-40F3-AAB3-9FB651FE45BB',
    'name': 'Gift Shop and Souvenirs'}],
  'topics': [{'id': '69693007-2DF2-4EDE-BB3B-A25EBA72BDF5',
    'name': 'Architecture and Building'},
   {'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B', 'name': 'Archeology'},
   {'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370', 'name': 'Arts'},
   {'id': '7F12224B-217A-4B07-A4A2-636B1CE7F221',
    'name': 'Colonization and Settlement'},
   {'id': '3B0D607D-9933-425A-BFA0-21529AC4734C', 'name': 'Military'},
   {'id': 'B145FAB8-5462-4FE2-964E-464D3A5E7F96', 'name': 'Artillery'},
   {'id': '97CCB419-196C-4B95-BB3A-621458F78415', 'name': 'US Army'},
   {'id': '2ACF7D12-91EA-4981-A1B7-AD0A186B6800', 'name': 'Armories'},
   {'id': 'A1BAF33E-EA84-4608-A888-4CEE9541F027',
    'name': 'Native American Heritage'},
   {'id': '3CDB67A9-1EAC-408D-88EC-F26FA35E90AF',
    'name': 'Schools and Education'},
   {'id': '40C0866A-3890-41A4-84CA-5935DEE181AE', 'name': 'Social Movements'},
   {'id': '4C0EBDE7-EB73-4252-84D9-0650974EC3E5',
    'name': 'Conservation Movement'},
   {'id': '27BF8807-54EA-4A3D-B073-AA7AA361CD7E',
    'name': 'Wars and Conflicts'},
   {'id': 'A764E57D-9925-4855-8D66-C60357946FC3', 'name': 'Cold War'},
   {'id': '0D00073E-18C3-46E5-8727-2F87B112DDC6', 'name': 'Animals'},
   {'id': '921D1471-5F6B-47D5-918D-389E7106083A',
    'name': 'Alligators or Crocodiles'},
   {'id': '957EF2BD-AC6C-4B7B-BD9A-87593ADC6691', 'name': 'Birds'},
   {'id': '2539614A-9646-446E-8251-34D3AAE068FA', 'name': 'Cats (wild)'},
   {'id': '1608649A-E7D7-4529-BD83-074C90F9FB68', 'name': 'Fish'},
   {'id': '393F60FB-80D6-46F7-B0FB-BBF3C90F59FD',
    'name': 'Tortoises and Turtles'},
   {'id': '4DC11D06-00F1-4A01-81D0-89CCCCE4FF50', 'name': 'Climate Change'},
   {'id': '46FC5CBD-9AD5-48F1-B4DA-1357031B1D2E',
    'name': 'Coasts, Islands and Atolls'},
   {'id': 'F79C1242-80FF-40F0-A0C1-5FFCBA172EC0',
    'name': 'Estuaries and Mangroves'},
   {'id': '04A39AB8-DD02-432F-AE5F-BA1267D41A0D', 'name': 'Fire'},
   {'id': 'F0F97E32-2F29-41B4-AF98-9FBE8DAB36B1', 'name': 'Geology'},
   {'id': '94262026-92F5-48E9-90EF-01CEAEFBA4FF', 'name': 'Grasslands'},
   {'id': '1AEDC86F-5792-487F-8CDF-9E92CAB97ACE', 'name': 'Prairies'},
   {'id': 'F8C2FE93-DEB3-4B12-9A87-913E3E6B448D', 'name': 'Natural Sounds'},
   {'id': 'A7359FC4-DAD8-45F5-AF15-7FF62F816ED3', 'name': 'Night Sky'},
   {'id': '0E6D8503-CB65-467F-BCD6-C6D9E28A4E0B', 'name': 'Oceans'},
   {'id': 'A155238F-0DD2-4610-9B87-05FCE1C59283',
    'name': 'River and Riparian'},
   {'id': '9C9FCBB6-360B-4743-8155-6F9341CBE01B', 'name': 'Scenic Views'},
   {'id': '5BE55D7F-BDB6-4E3D-AC35-2D8EBB974417', 'name': 'Trails'},
   {'id': '596BAA6D-F66B-4348-8433-FEFF35A8005E', 'name': 'Water Trails'},
   {'id': '78E4F4AC-AF97-435A-8C2C-7FB8D67516ED', 'name': 'Unique Species'},
   {'id': '996BEDAE-CB23-4003-B008-3A1F46A72263', 'name': 'Rare'},
   {'id': '489D6333-FD72-44DF-83B0-3D4412DD0A75', 'name': 'Endangered'},
   {'id': '1365C347-952C-475A-B755-731DD523C195', 'name': 'Wetlands'},
   {'id': 'FD0BA21A-5F69-4688-9D4B-856DA242DC78', 'name': 'Marshes'},
   {'id': 'B85866E2-0897-4000-9040-605CA335804F', 'name': 'Wilderness'}],
  'states': 'FL',
  'contacts': {'phoneNumbers': [{'phoneNumber': '3052427700',
     'description': '',
     'extension': '',
     'type': 'Voice'},
    {'phoneNumber': '3052427728',
     'description': '',
     'extension': '',
     'type': 'Fax'}],
   'emailAddresses': [{'description': '',
     'emailAddress': 'ever_information@nps.gov'}]},
  'entranceFees': [{'cost': '35.00',
    'description': 'Admits the passholder and passengers of a single vehicle or vessel. Good for 7 consecutive days at all park entrances.',
    'title': 'Entrance - Private Vehicle'},
   {'cost': '30.00',
    'description': 'Good for 7 consecutive days at all park entrances.',
    'title': 'Entrance - Motorcycle'},
   {'cost': '20.00',
    'description': 'Good for 7 consecutive days at all park entrances. Admits one individual hiker, bicyclist, pedestrian, or human-powered paddlecraft, when not arriving in a vehicle or vessel. Individuals 15 years old and younger, are admitted free of charge.',
    'title': 'Entrance - Per Person'},
   {'cost': '0.00',
    'description': 'All accredited educational and scientific institutions are eligible to receive free entrance to the park. Bringing your classroom to the park can present many unique learning opportunities and novel ways for your students to advance their studies. The Federal Lands Recreation Enhancement Act (FLREA), Public Law 108-447, provides the National Park Service statutory authority to allow “outings conducted for non-commercial educational purposes by schools or bona fide academic institutions.”',
    'title': 'Entrance - Education/Academic Groups'},
   {'cost': '300.00',
    'description': 'A commercial tour is defined as persons traveling on an itinerary that has been packaged, priced or sold for leisure recreational purposes by an organization that realizes financial gain through the provisions of the service. Entrance fees are charges based on the seating capacity of the vehicle. Commercial entry good for 7 days as long as its the same passenger group.',
    'title': 'Commercial Entrance - Motor Coach'},
   {'cost': '200.00',
    'description': 'A commercial tour is defined as persons traveling on an itinerary that has been packaged, priced or sold for leisure recreational purposes by an organization that realizes financial gain through the provisions of the service. Entrance fees are charges based on the seating capacity of the vehicle. Commercial entry good for 7 days as long as its the same passenger group.',
    'title': 'Commercial Entrance - Mini-bus'},
   {'cost': '125.00',
    'description': 'A commercial tour is defined as persons traveling on an itinerary that has been packaged, priced or sold for leisure recreational purposes by an organization that realizes financial gain through the provisions of the service. Entrance fees are charges based on the seating capacity of the vehicle. Commercial entry good for 7 days as long as its the same passenger group.',
    'title': 'Commercial Entrance - Van'}],
  'entrancePasses': [{'cost': '70.00',
    'description': 'The Everglades Annual Pass admits the pass holder, passenger on one motorcycle, or passengers of a single vehicle or vessel to Everglades National Park.',
    'title': 'Annual Entrance - Park'}],
  'fees': [],
  'directionsInfo': 'Directions to Ernest Coe Visitor Center 40001 State Road 9336, Homestead, FL 33034 Visitors coming from the Miami area and points north should take the Florida Turnpike (Route 821) south until it ends merging with U.S. 1 at Florida City. Turn right at the first traffic light onto Palm Drive (State Road 9336/SW 344th St.) and follow the signs to the park. Visitors driving north from the Florida Keys should turn left on Palm Drive in Florida City and follow the signs to the park.',
  'directionsUrl': 'http://www.nps.gov/ever/planyourvisit/directions.htm',
  'operatingHours': [{'exceptions': [],
    'description': 'Everglades National Park is open 7 days a week, 24 hours a day. Park entrance is always open but staffed from 8:00 a.m. to 4:30 p.m.',
    'standardHours': {'wednesday': 'All Day',
     'monday': 'All Day',
     'thursday': 'All Day',
     'sunday': 'All Day',
     'tuesday': 'All Day',
     'friday': 'All Day',
     'saturday': 'All Day'},
    'name': 'Everglades National Park'}],
  'addresses': [{'postalCode': '33034',
    'city': 'Homestead',
    'stateCode': 'FL',
    'countryCode': 'US',
    'provinceTerritoryCode': '',
    'line1': '40001 State Road 9336',
    'type': 'Physical',
    'line3': '',
    'line2': ''},
   {'postalCode': '33034-6733',
    'city': 'Homestead',
    'stateCode': 'FL',
    'countryCode': 'US',
    'provinceTerritoryCode': '',
    'line1': '40001 State Road 9336',
    'type': 'Mailing',
    'line3': '',
    'line2': ''}],
  'images': [{'credit': 'NPS Photo by Miguel Salas',
    'title': 'Cypress Tree Sunrise',
    'altText': "A sunset creates a silhouette of a cypress tree with needle-like leaves that is shaped like an 'N'.",
    'caption': 'Cypress Tree Sunrise (2020 Photo Contest)',
    'url': 'https://www.nps.gov/common/uploads/structured_data/17EC840E-9926-2E09-F2DD47A282915BBB.jpg'},
   {'credit': 'NPS Photo',
    'title': 'Nine Mile Pond',
    'altText': 'Two canoes at Nine Mile Pond during sunset.',
    'caption': 'A meeting ground of marsh and mangrove environments. You may see alligators, wading birds, turtles, and fish.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C854681-1DD8-B71B-0BA4F6D9379336DF.jpg'},
   {'credit': 'NPS Photo',
    'title': 'American Alligator',
    'altText': 'An American Alligator high walks the Anhinga Trail.',
    'caption': 'An American Alligator high walks the Anhinga Trail.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C8547ED-1DD8-B71B-0B596F29F0A9A60B.jpg'},
   {'credit': 'NPS Photo',
    'title': 'Shark Valley Tram and Bicycle Road',
    'altText': 'Two visitors bike along the road in Shark Valley.',
    'caption': 'Biking is a great way to experience the quiet beauty of the Everglades.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85E60F-1DD8-B71B-0BAB4F7583E96025.jpg'},
   {'credit': 'NPS Photo',
    'title': 'Transition from Sawgrass to Florida Bay',
    'altText': 'An aerial view of the landscape transition from Sawgrass to Florida Bay.',
    'caption': 'An aerial view of the landscape transition from Sawgrass to Florida Bay.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85E70B-1DD8-B71B-0B7C75649CCDB907.jpg'},
   {'credit': 'NPS Photo',
    'title': 'Camping at Long Pine Key',
    'altText': 'Three tents are put up along the Long Pine Key campsite.',
    'caption': 'Long Pine Key Campground is open seasonally from November through May. It is located seven miles (11 km) from the main entrance, just off the main road.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85F532-1DD8-B71B-0BFC5BB51D8AB675.jpg'}],
  'weatherInfo': 'The climate in Florida is known to be mild and sunny.The average annual temperatures for South Florida and the Keys range from 74° to 77°F (23° to 25°C). There are two seasons at the Everglades National Park: the wet season and the dry season. The wet season runs from Mid-May to November and the dry season runs from December to mid-May.',
  'name': 'Everglades',
  'designation': 'National Park',
  'multimedia': [],
  'relevanceScore': 1.0}]

In [144]:
lang_chat(question)

'The address of Everglades National Park is 40001 State Road 9336, Homestead, FL 33034, United States.'

In [145]:
gpt_chat(question)

'The Everglades National Park is located in Florida, and the main entrance address is 40001 State Road 9336, Homestead, FL 33034.'

#### Alerts

In [146]:
question ='What alerts are at bryce?'
get_context(question, model)

[{'id': '9840308A-02FB-4A2F-90A3-E5597EB3881B',
  'url': 'https://www.nps.gov/brca/planyourvisit/conditions.htm',
  'title': 'Main Road Status',
  'parkCode': 'brca',
  'description': 'The main park road is fully open to Rainbow Point (Mile 18 of 18). All park roads are currently open for the season. During snowstorms the road may temporarily close at Mile 3 for snowplow operations.',
  'category': 'Information',
  'relatedRoadEvents': [],
  'lastIndexedDate': '2024-04-02 13:59:18.0'},
 {'id': '8833A24A-3F71-4E6E-9254-FF7743304115',
  'url': 'https://www.nps.gov/brca/planyourvisit/basicinfo.htm',
  'title': 'Bryce Canyon is Open - No Reservations Required to Enter',
  'parkCode': 'brca',
  'description': 'No reservations are required to enter Bryce Canyon National Park at any time of year. Simply pay your park entrance fee or present your America the Beautiful pass upon arrival.',
  'category': 'Information',
  'relatedRoadEvents': [],
  'lastIndexedDate': '2024-02-16 15:58:11.0'}]

In [147]:
lang_chat(question)

'There are currently no alerts at Bryce Canyon National Park. The main park road is fully open to Rainbow Point, and all park roads are currently open for the season.'

In [148]:
gpt_chat(question)

"At Bryce Canyon National Park, visitors should be aware of alerts related to weather conditions, trail closures, wildlife encounters, and safety reminders. It's always a good idea to check the park's official website or contact the visitor center for the most up-to-date information on any alerts or advisories in the park."

#### Fees

In [7]:
question ='What are the fees for grand canyon?'
get_context(question, model)

[{'parkCode': 'grca',
  'isFeeFreePark': False,
  'isInteragencyPassAccepted': True,
  'cashless': 'Yes',
  'feesAtWorkUrl': '',
  'entranceFeeDescription': "Admission to Grand Canyon National Park is for seven days and includes both the South Rim and during their season, the North Rim. No cash is accepted; credit/debit card only. No refunds are given due to inclement weather. Grand Canyon Annual Passes and America the Beautiful passes are available at all three of Grand Canyon National Park's entrance stations.",
  'entrancePassDescription': 'Grand Canyon National Park - Annual Pass Available to the general public for purchase for unlimited visits to Grand Canyon National Park only. This is an annual pass, valid one year from month of purchase; it is non-transferable. It admits the pass holder and any accompanying persons in a single, private, non-commercial vehicle, or the pass holder and accompanying immediate family (spouse, children, parents) when entry is by other means (train, shuttle, bicycle, or foot).',
  'isParkingFeePossible': False,
  'parkingDetailsUrl': '',
  'timedEntryHeading': '',
  'timedEntryDescription': '',
  'isParkingOrTransportationFeePossible': False,
  'paidParkingHeading': '',
  'paidParkingDescription': '',
  'customFeeHeading': '',
  'customFeeDescription': '',
  'customFeeLinkUrl': '',
  'customFeeLinkText': '',
  'contentOrderOrdinals': {'entranceFee': 1,
   'timedEntry': 1,
   'paidParking': 1,
   'customFee': 4},
  'relatedMultiSitePasses': [],
  'fees': [{'entranceFeeType': 'Entrance - Private Vehicle',
    'startDate': {'month': 1, 'holiday': None, 'day': 1},
    'paymentDescription': 'No cash is accepted; credit/debit card only. No refunds are given due to inclement weather.',
    'recGovPurchaseUrl': '',
    'timedEntryLocation': '',
    'endDate': {'month': 12, 'holiday': None, 'day': 31},
    'exceptions': '',
    'payGovPurchaseUrl': '',
    'cost': '35.00',
    'timedEntryShortDescription': '',
    'description': 'Admits one single, private, non-commercial vehicle and all its passengers, up to a 15 person passenger van. Organized non-commercial groups over 16 passengers require different charges. Commercial groups are not eligible for the vehicle permit.',
    'informationUrl': '',
    'id': 'A618BAEE-5F9A-4985-B245-FE850CD9FFF5',
    'npsGovPurchaseUrl': ''},
   {'entranceFeeType': 'Entrance - Motorcycle',
    'startDate': {'month': 1, 'holiday': None, 'day': 1},
    'paymentDescription': '',
    'recGovPurchaseUrl': '',
    'timedEntryLocation': '',
    'endDate': {'month': 12, 'holiday': None, 'day': 31},
    'exceptions': '',
    'payGovPurchaseUrl': '',
    'cost': '30.00',
    'timedEntryShortDescription': '',
    'description': 'Admits one single, private, non-commercial motorcycle and its passenger(s).',
    'informationUrl': '',
    'id': '8832038A-0E67-4E17-95BA-570DEF4F786F',
    'npsGovPurchaseUrl': ''},
   {'entranceFeeType': 'Entrance - Per Person',
    'startDate': {'month': 1, 'holiday': None, 'day': 1},
    'paymentDescription': '',
    'recGovPurchaseUrl': '',
    'timedEntryLocation': '',
    'endDate': {'month': 12, 'holiday': None, 'day': 31},
    'exceptions': '',
    'payGovPurchaseUrl': '',
    'cost': '20.00',
    'timedEntryShortDescription': '',
    'description': 'Individual ($20 valid for 7 days): for bicyclists, hikers, and pedestrians.',
    'informationUrl': '',
    'id': '30CDC605-86C2-4AAB-86C8-832F373DFCE4',
    'npsGovPurchaseUrl': ''}],
  'passes': [{'exceptions': '',
    'payGovPurchaseUrl': '',
    'cost': '70.00',
    'image': [{'credit': 'Photo/Roderic Rieman',
      'title': 'Grand Canyon National Park Annual Pass',
      'altText': 'a variety of clouds above a vast landscape of peaks and cliffs that is mostly in shadow',
      'caption': 'Grand Canyon National Park 2023 Annual Pass.',
      'url': 'https://www.nps.gov/common/uploads/entrance_pass/E11B0B21-B31F-E94E-C446AC6DF5913968.jpg'}],
    'description': 'Available to the general public for purchase for unlimited visits to Grand Canyon National Park only. This is an annual pass, valid one year from month of purchase; it is non-transferable.\n\nIt admits the pass holder and any accompanying persons in a single, private, non-commercial vehicle, or the pass holder and accompanying immediate family (spouse, children, parents) when entry is by other means (train, shuttle, bicycle, or foot).',
    'paymentDescription': '',
    'category': 'Annual Entrance - Park',
    'informationUrl': '',
    'recGovPurchaseUrl': '',
    'id': '569163EC-3638-4EA5-842A-1936EA1EE937',
    'npsGovPurchaseUrl': ''}]}]

In [12]:
lang_chat(question)

'The fees for Grand Canyon National Park are as follows:\n- Entrance fee for a private vehicle: $35.00\n- Entrance fee for a motorcycle: $30.00\n- Entrance fee per person (bicyclists, hikers, pedestrians): $20.00\n\nAdditionally, there is an option to purchase an Annual Pass for unlimited visits to Grand Canyon National Park for $70.00.'

In [13]:
gpt_chat(question)

'The entrance fee for Grand Canyon National Park is $35 per vehicle, which is valid for 7 days. There are also other pass options available, such as the annual pass for $70, which provides access to all national parks for one year. Additionally, there are discounts available for seniors, military members, and other groups.'

Full Name

In [29]:
question ='What is the full name of joshua park?'
get_context(question, model)

[{'id': 'F5CD58FB-05DC-4074-99DA-F327A537F1BC',
  'url': 'https://www.nps.gov/jotr/index.htm',
  'fullName': 'Joshua Tree National Park',
  'parkCode': 'jotr',
  'description': 'Two distinct desert ecosystems, the Mojave and the Colorado, come together in Joshua Tree National Park. A fascinating variety of plants and animals make their homes in a land sculpted by strong winds and occasional torrents of rain. Dark night skies, a rich cultural history, and surreal geologic features add to the wonder of this vast wilderness in southern California. Come explore for yourself!',
  'latitude': '33.91418525',
  'longitude': '-115.8398125',
  'latLong': 'lat:33.91418525, long:-115.8398125',
  'activities': [{'id': '5F723BAD-7359-48FC-98FA-631592256E35',
    'name': 'Auto and ATV'},
   {'id': '0B4A5320-216D-451A-9990-626E1D5ACE28', 'name': 'Scenic Driving'},
   {'id': '13A57703-BB1A-41A2-94B8-53B692EB7238', 'name': 'Astronomy'},
   {'id': 'D37A0003-8317-4F04-8FB0-4CF0A272E195', 'name': 'Stargazing'},
   {'id': '7CE6E935-F839-4FEC-A63E-052B1DEF39D2', 'name': 'Biking'},
   {'id': 'A59947B7-3376-49B4-AD02-C0423E08C5F7', 'name': 'Camping'},
   {'id': '4A58AF13-E8FB-4530-B41A-97DF0B0C77B7',
    'name': 'Backcountry Camping'},
   {'id': '9159DF0F-951D-4AAE-9987-CEB3CE2A9ADA',
    'name': 'Car or Front Country Camping'},
   {'id': '80229F2D-972E-40A8-8860-232551CC30D6',
    'name': 'Horse Camping (see also Horse/Stock Use)'},
   {'id': '7CFF5F03-5ECC-4F5A-8572-75D1F0976C0C', 'name': 'Group Camping'},
   {'id': 'B12FAAB9-713F-4B38-83E4-A273F5A43C77', 'name': 'Climbing'},
   {'id': '87D3B1CD-3903-4561-ABB1-2DD870C43F2F', 'name': 'Rock Climbing'},
   {'id': '1DFACD97-1B9C-4F5A-80F2-05593604799E', 'name': 'Food'},
   {'id': 'C6D3230A-2CEA-4AFE-BFF3-DC1E2C2C4BB4', 'name': 'Picnicking'},
   {'id': 'B33DC9B6-0B7D-4322-BAD7-A13A34C584A3', 'name': 'Guided Tours'},
   {'id': 'A0631906-9672-4583-91DE-113B93DB6B6E',
    'name': 'Self-Guided Tours - Walking'},
   {'id': 'C7D5A145-F8EB-4C37-9E92-2F6C6206B196',
    'name': 'Self-Guided Tours - Auto'},
   {'id': 'BFF8C027-7C8F-480B-A5F8-CD8CE490BFBA', 'name': 'Hiking'},
   {'id': '7C37B79B-D02D-49EB-9020-3DB8299B748A',
    'name': 'Backcountry Hiking'},
   {'id': '45261C0A-00D8-4C27-A1F8-029F933A0D34',
    'name': 'Front-Country Hiking'},
   {'id': '0307955A-B65C-4CE4-A780-EB36BAAADF0B', 'name': 'Horse Trekking'},
   {'id': '788C7572-5425-49EF-A0BF-5A0DF93F7542',
    'name': 'Horse Camping (see also camping)'},
   {'id': '1886DA47-0AEC-4568-B9C2-8E9BC316AAAC', 'name': 'Horseback Riding'},
   {'id': 'DF4A35E0-7983-4A3E-BC47-F37B872B0F25',
    'name': 'Junior Ranger Program'},
   {'id': '0B685688-3405-4E2A-ABBA-E3069492EC50', 'name': 'Wildlife Watching'},
   {'id': '5A2C91D1-50EC-4B24-8BED-A2E11A1892DF', 'name': 'Birdwatching'},
   {'id': 'C8F98B28-3C10-41AE-AA99-092B3B398C43', 'name': 'Museum Exhibits'},
   {'id': '24380E3F-AD9D-4E38-BF13-C8EEB21893E7', 'name': 'Shopping'},
   {'id': '467DC8B8-0B7D-436D-A026-80A22358F615',
    'name': 'Bookstore and Park Store'}],
  'topics': [{'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B',
    'name': 'Archeology'},
   {'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370', 'name': 'Arts'},
   {'id': '9BD60DC0-C82B-42BA-A170-456B7423429D', 'name': 'Photography'},
   {'id': '1F833C99-A75D-4F9E-9256-B96523485466',
    'name': 'Farming and  Agriculture'},
   {'id': 'E4E84C87-6737-4C37-9157-5962648A35F2', 'name': 'Ranches'},
   {'id': '0B575E33-B68F-4F3D-998E-B03284606CF3', 'name': 'Industry'},
   {'id': 'BDC806A8-5470-4A8B-A0F9-CD804BE3028A', 'name': 'Mining'},
   {'id': 'A1BAF33E-EA84-4608-A888-4CEE9541F027',
    'name': 'Native American Heritage'},
   {'id': 'C9C749E3-39C3-45F7-BCC5-9A609E30AA05',
    'name': 'Westward Expansion'},
   {'id': 'D1722DD1-E314-4B6D-8116-DED86305C4A4', 'name': 'Homesteading'},
   {'id': '0D00073E-18C3-46E5-8727-2F87B112DDC6', 'name': 'Animals'},
   {'id': '957EF2BD-AC6C-4B7B-BD9A-87593ADC6691', 'name': 'Birds'},
   {'id': '393F60FB-80D6-46F7-B0FB-BBF3C90F59FD',
    'name': 'Tortoises and Turtles'},
   {'id': '4DC11D06-00F1-4A01-81D0-89CCCCE4FF50', 'name': 'Climate Change'},
   {'id': '04A39AB8-DD02-432F-AE5F-BA1267D41A0D', 'name': 'Fire'},
   {'id': 'F0F97E32-2F29-41B4-AF98-9FBE8DAB36B1', 'name': 'Geology'},
   {'id': '4BE01DC5-52E6-4F18-8C9A-B22D65965F6D', 'name': 'Groundwater'},
   {'id': '0E1A04CC-EB51-4F18-93D4-EC0B0B4EC1E3',
    'name': 'Freshwater Springs'},
   {'id': 'A7359FC4-DAD8-45F5-AF15-7FF62F816ED3', 'name': 'Night Sky'},
   {'id': '5BE55D7F-BDB6-4E3D-AC35-2D8EBB974417', 'name': 'Trails'},
   {'id': '78E4F4AC-AF97-435A-8C2C-7FB8D67516ED', 'name': 'Unique Species'},
   {'id': '489D6333-FD72-44DF-83B0-3D4412DD0A75', 'name': 'Endangered'},
   {'id': 'B85866E2-0897-4000-9040-605CA335804F', 'name': 'Wilderness'}],
  'states': 'CA',
  'contacts': {'phoneNumbers': [{'phoneNumber': '7603675500',
     'description': '',
     'extension': '',
     'type': 'Voice'},
    {'phoneNumber': '7603676392',
     'description': '',
     'extension': '',
     'type': 'Fax'}],
   'emailAddresses': [{'description': '',
     'emailAddress': 'jotr_info@nps.gov'}]},
  'entranceFees': [{'cost': '30.00',
    'description': '7-day vehicle permit, admitting the passengers of a single, non-commercial vehicle on the day of purchase and for the next six days.',
    'title': 'Entrance - Private Vehicle'},
   {'cost': '25.00',
    'description': '7-day entrance permit, per motorcycle.',
    'title': 'Entrance - Motorcycle'},
   {'cost': '15.00',
    'description': '7-day entrance fee, per person on foot or bike.',
    'title': 'Entrance - Per Person'}],
  'entrancePasses': [{'cost': '55.00',
    'description': 'This pass is valid for 12 months from the month of purchase. It covers the entrance fee to Joshua Tree National Park for the pass signee and accompanying passengers entering in a single, non-commercial vehicle. Joshua Tree Annual Passes are available at park entrance stations and visitor centers.',
    'title': 'Annual Entrance - Park'}],
  'fees': [],
  'directionsInfo': "From I-10, take exit 117 for CA Hwy 62 toward 29 Palms/Yucca Valley. This will allow you to access the West Entrance, the North Entrance, Black Rock, and Indian Cove. Take exit 168 off I-10 to come in at the park's South Entrance.",
  'directionsUrl': 'http://www.nps.gov/jotr/planyourvisit/directions.htm',
  'operatingHours': [{'exceptions': [],
    'description': 'Joshua Tree National Park is open 24 hours a day, 7 days a week, 365 days a year. Visitation increases as temperatures moderate in the fall, peaks during the spring wildflower season, and diminishes during the heat of summer. Some areas of the park are designated for day use only. Visitor centers keep separate hours; please see descriptions.',
    'standardHours': {'wednesday': 'All Day',
     'monday': 'All Day',
     'thursday': 'All Day',
     'sunday': 'All Day',
     'tuesday': 'All Day',
     'friday': 'All Day',
     'saturday': 'All Day'},
    'name': 'Joshua Tree National Park'}],
  'addresses': [{'postalCode': '92277-3597',
    'city': 'Twentynine Palms',
    'stateCode': 'CA',
    'countryCode': 'US',
    'provinceTerritoryCode': '',
    'line1': '74485 National Park Drive',
    'type': 'Physical',
    'line3': '',
    'line2': ''},
   {'postalCode': '92277-3597',
    'city': 'Twentynine Palms',
    'stateCode': 'CA',
    'countryCode': 'US',
    'provinceTerritoryCode': '',
    'line1': '74485 National Park Drive',
    'type': 'Mailing',
    'line3': '',
    'line2': ''}],
  'images': [{'credit': 'NPS / Emily Hassell',
    'title': 'Quail Springs Area at Sunset',
    'altText': 'The sky turns hues of pink and purple over a field of Joshua trees.',
    'caption': 'Quail Springs area at sunset',
    'url': 'https://www.nps.gov/common/uploads/structured_data/306D0D93-9CCA-76E1-AD48268F8D7A7E3E.jpg'},
   {'credit': 'NPS/Hannah Schwalbe',
    'title': 'Hidden Valley Hiker',
    'altText': 'hiker looks over Hidden Valley',
    'caption': 'Scrambling to the top of boulders in Joshua Tree can get you a great view.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85E84D-1DD8-B71B-0B188E7820D60F14.jpg'},
   {'credit': 'NPS/Kurt Moses',
    'title': 'Historic Keys Ranch',
    'altText': 'an historic wood house seen through the missing windshield of an old, rusty vehicle',
    'caption': 'The historic Keys Ranch can be visited only on a ranger-guided tour.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85EA46-1DD8-B71B-0B28B646B53F0C37.jpg'},
   {'credit': 'NPS/Brad Sutton',
    'title': 'Lost Horse Valley',
    'altText': 'Joshua trees grow on a flat plain with boulder outcrops and mountains in the distance',
    'caption': "Take in views of the park's iconic Joshua trees and rock outcrops in Lost Horse Valley.",
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85EF02-1DD8-B71B-0B467F2B5F7483AC.jpg'},
   {'credit': 'NPS/Kurt Moses',
    'title': 'Joshua Tree Junior Ranger',
    'altText': 'a little girl smiles while wearing a Jr. Ranger hat and badge',
    'caption': "Kids of all ages can take part in Joshua Tree National Park's Junior Ranger program.",
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85EC5C-1DD8-B71B-0B3B00469411625A.jpg'},
   {'credit': 'NPS/Brad Sutton',
    'title': 'Joshua Tree Sunset',
    'altText': 'a fiery sky behind the silhouette of a Joshua tree',
    'caption': 'The wide-open desert of Joshua Tree National Park makes for stunning sunsets.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85E941-1DD8-B71B-0BCAA9F8A0BD4E0F.jpg'},
   {'credit': 'NPS/Brad Sutton',
    'title': 'Jumbo Rocks at Sunset',
    'altText': 'people climbing on boulders are silhouetted against a colorful sunset sky',
    'caption': "Jumbo Rocks Campground is a fun place to explore the park's bouldered landscape.",
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85EDAE-1DD8-B71B-0B3E7EAC7E299A23.jpg'},
   {'credit': 'NPS/Lian Law',
    'title': 'Stars Over the Park Entrance',
    'altText': 'night scene showing stars of the Milky Way over a sign saying "Entering Joshua Tree National Park"',
    'caption': 'Enjoy some of the darkest night skies in Southern California.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85EB5A-1DD8-B71B-0BACA59CC5E5A620.jpg'}],
  'weatherInfo': 'Days are typically clear with less than 25% humidity. Temperatures are most comfortable in the spring and fall, with an average highs around 85°F (29°C) and average lows around 50°F (10°C) respectively. Winter brings cooler days, around 60°F (15°C), and freezing nights. It occasionally snows at higher elevations. Summers are hot, over 100°F (38°C) during the day and not cooling much below 75°F (24°C) at night.',
  'name': 'Joshua Tree',
  'designation': 'National Park',
  'multimedia': [{'title': 'Desert Tortoise 101',
    'id': '94DF562F-4500-4BFF-8E56-6C0A6012700A',
    'type': 'multimedia/video',
    'url': 'https://www.nps.gov/media/video/view.htm?id=94DF562F-4500-4BFF-8E56-6C0A6012700A'},
   {'title': 'Granite Desk: Adaptations',
    'id': '34C6CF7B-2A2D-4AC5-A358-07C67CEDD4C8',
    'type': 'multimedia/video',
    'url': 'https://www.nps.gov/media/video/view.htm?id=34C6CF7B-2A2D-4AC5-A358-07C67CEDD4C8'},
   {'title': 'Granite Desk: Geology',
    'id': 'FBE15594-1966-4C9D-A7A0-8AC0B0D24130',
    'type': 'multimedia/video',
    'url': 'https://www.nps.gov/media/video/view.htm?id=FBE15594-1966-4C9D-A7A0-8AC0B0D24130'},
   {'title': 'Mesquite Processing Documentary ',
    'id': '3F3E027A-46CD-4FDB-A690-6AE9A2E37E97',
    'type': 'multimedia/video',
    'url': 'https://www.nps.gov/media/video/view.htm?id=3F3E027A-46CD-4FDB-A690-6AE9A2E37E97'},
   {'title': 'Joshua Tree Scenery',
    'id': '370FFDB9-FE58-9281-ECF4-B906ED525F1A',
    'type': 'multimedia/galleries',
    'url': 'https://www.nps.gov/media/photo/gallery.htm?id=370FFDB9-FE58-9281-ECF4-B906ED525F1A'},
   {'title': 'Night at Joshua Tree National Park',
    'id': '4F42E474-C959-454E-A46D-EAC6D43BB603',
    'type': 'multimedia/galleries',
    'url': 'https://www.nps.gov/media/photo/gallery.htm?id=4F42E474-C959-454E-A46D-EAC6D43BB603'}],
  'relevanceScore': 1.0}]

In [33]:
lang_chat(question)

'The full name of the park is Joshua Tree National Park.'

In [34]:
gpt_chat(question)

'The full name of Joshua Tree National Park is Joshua Tree National Park.'

Amenities

In [35]:
question ='What amenities are at bryce canyon?'
get_context(question, model)

[{'id': 'A1B0AD01-740C-41E7-8412-FBBEDD5F1443',
  'name': 'ATM/Cash Machine',
  'categories': ['Convenience', 'Souvenirs and Supplies']},
 {'id': '4E4D076A-6866-46C8-A28B-A129E2B8F3DB',
  'name': 'Accessible Rooms',
  'categories': ['Accessibility']},
 {'id': 'B509969B-F06A-4DCC-BBB3-134964D896E2',
  'name': 'Amphitheater',
  'categories': ['Interpretive', 'Recreation']},
 {'id': 'CBD31D2A-DD1A-4C5D-88C1-67B6B7147CE9',
  'name': 'Assistive Listening Systems',
  'categories': ['Accessibility']},
 {'id': '7DC6C690-2BC3-4344-9691-EF9FCFB6E506',
  'name': 'Audio Description',
  'categories': ['Accessibility']},
 {'id': 'F4A842CB-C966-402E-BBD3-AB86EDCF8403',
  'name': 'Automated Entrance',
  'categories': ['Accessibility']},
 {'id': 'B166EAD1-0D3E-4111-AE04-D5AB15DFDEDC',
  'name': 'Baby Changing Station',
  'categories': ['Convenience']},
 {'id': '20291812-E85C-4A84-B8A2-E31C8D149704',
  'name': 'Benches/Seating',
  'categories': ['Convenience']},
 {'id': '5BDFF349-2F74-490E-A33E-C35286152050',
  'name': 'Bicycle - Rack',
  'categories': ['Biking', 'Recreation']},
 {'id': 'EDA44DDD-DC61-4EAE-84AD-78FA52D98406',
  'name': 'Bicycle - Rental',
  'categories': ['Biking', 'Recreation', 'Transportation']},
 {'id': '27A7E3AB-CA53-41D3-AEDE-FBF74D20F023',
  'name': 'Braille',
  'categories': ['Accessibility']},
 {'id': 'DA9F2E5C-E46B-4F62-893E-4364D35931DC',
  'name': 'Bus/Shuttle Stop',
  'categories': ['Transportation']},
 {'id': '3B84C2C8-E890-4EE5-B0E7-FA157EFD8DAC',
  'name': 'Captioned Media',
  'categories': ['Accessibility']},
 {'id': '48562BFB-834B-43F2-B865-E174C372032B',
  'name': 'Cellular Signal',
  'categories': ['Convenience']},
 {'id': '1C1B932D-32B6-4BAA-8AA6-497F08CC22BF',
  'name': 'Electrical Outlet/Cell Phone Charging',
  'categories': ['Convenience']},
 {'id': '1D08E7AD-5634-4185-80F4-B4C3CB5BD927',
  'name': 'Entrance Passes for Sale',
  'categories': ['Permits and Passes']},
 {'id': '802BE109-511F-47D9-84D5-18DDA1C90771',
  'name': 'Fire Extinguisher',
  'categories': ['Emergency', 'Safety']},
 {'id': '28BF85F5-E93F-4EF1-A89B-05C99FCD808A',
  'name': 'Firewood For Sale/Available',
  'categories': ['Souvenirs and Supplies']},
 {'id': '2DEE6458-72F8-4C97-9279-5C3E90B19888',
  'name': 'First Aid/Medical Care Available',
  'categories': ['Emergency', 'Safety']},
 {'id': '383F944C-35BA-43E3-8EEA-24953836B8C5',
  'name': 'Food/Drink - Bar/Alcohol For Sale',
  'categories': ['Food']},
 {'id': '5D1ADBE5-E75D-4657-9577-FB5A6A90C7F9',
  'name': 'Food/Drink - Coffee',
  'categories': ['Food']},
 {'id': '3B482494-83EF-48D9-A626-FC00EFD4F4A4',
  'name': 'Food/Drink - Ice Cream',
  'categories': ['Food']},
 {'id': '2F798138-5D0A-468E-96DA-0A07F03031B0',
  'name': 'Food/Drink - Restaurant/Table Service',
  'categories': ['Food']},
 {'id': '29D286B6-069C-4204-AF35-AE7744B71212',
  'name': 'Food/Drink - Snacks',
  'categories': ['Food', 'Souvenirs and Supplies']},
 {'id': '4F26643C-FAAF-40CE-85F7-38DEC4746BE6',
  'name': 'Food/Drink - Vending Machine/Self Service',
  'categories': ['Food', 'Souvenirs and Supplies']},
 {'id': '3476E39B-5402-4999-99B3-AC8F030629E7',
  'name': 'Gifts/Souvenirs/Books',
  'categories': ['Convenience', 'Souvenirs and Supplies']},
 {'id': '6E639F57-CC17-40FB-B6A0-452652066187',
  'name': 'Grill',
  'categories': ['Picnic']},
 {'id': '8741D9DE-239A-4739-9920-4844BB587E6A',
  'name': 'Groceries/Convenience Items',
  'categories': ['Convenience', 'Food', 'Souvenirs and Supplies']},
 {'id': '2856392B-17A7-4413-8521-C13A8D2188EB',
  'name': 'Historical/Interpretive Information/Exhibits',
  'categories': ['Interpretive']},
 {'id': 'EC76D4B1-F391-45EB-AEC4-DC96B3F58194',
  'name': 'Ice',
  'categories': ['Souvenirs and Supplies']},
 {'id': '0AF7920C-2F54-42A7-88CA-F2EEBCB15655',
  'name': 'Information',
  'categories': ['Information Available']},
 {'id': '7E66CA2E-40AD-487E-8A04-8A9A2E4897C9',
  'name': 'Information - Maps Available',
  'categories': ['Convenience', 'Information Available']},
 {'id': '6815A395-2988-4AF3-8006-50224AD05193',
  'name': 'Information - Park Newspaper Available',
  'categories': ['Information Available']},
 {'id': '8320DDEA-91E7-411D-81B4-5D31CCA2267B',
  'name': 'Information - Ranger/Staff Member Present',
  'categories': ['Information Available']},
 {'id': '80E207D6-E9C3-4075-9823-26D23E963FA2',
  'name': 'Information Kiosk/Bulletin Board',
  'categories': ['Information Available']},
 {'id': '9EA123B3-E118-4BE9-BF49-EE93F1BA645B',
  'name': 'Internet/WiFi Available',
  'categories': ['Convenience']},
 {'id': 'B108A32A-52A4-4C4E-B178-0276BFBD9555',
  'name': 'Laundry',
  'categories': ['Convenience']},
 {'id': '6297C73A-5B8D-4D0E-BAD1-5E47F244D20A',
  'name': 'Low-Vision Access',
  'categories': ['Accessibility']},
 {'id': '163C13BC-0AD5-4190-8D1F-0B7E2C1B0BA3',
  'name': 'Open Captioning',
  'categories': ['Accessibility']},
 {'id': 'B760D6E2-3616-4D8B-ABF2-B875B7966831',
  'name': 'Parking - Auto',
  'categories': ['Parking']},
 {'id': 'EDA1E992-DA2B-4933-A7AD-23E3B7BFA602',
  'name': 'Parking - Boat Trailer',
  'categories': ['Boating', 'Parking']},
 {'id': '0965B1F3-A824-4A31-98C9-86CCD2889220',
  'name': 'Parking - Bus/RV',
  'categories': ['Parking']},
 {'id': '24140B47-F8FE-4046-BB6A-817F9E165959',
  'name': 'Permits Issued',
  'categories': ['Permits and Passes']},
 {'id': '6B68B30A-40C9-4745-9397-4899B59B0B7E',
  'name': 'Picnic Table',
  'categories': ['Picnic', 'Recreation']},
 {'id': 'A0038A57-E213-46E7-BD5F-40E9AE18014F',
  'name': 'Public Transit',
  'categories': ['Transportation']},
 {'id': '4706077B-00CB-4D07-80C7-48B2D5ADEFA2',
  'name': 'Recycling',
  'categories': ['Convenience']},
 {'id': '2883D965-1CA4-4858-B759-A5866CA8A188',
  'name': 'Restroom',
  'categories': ['Restrooms']},
 {'id': '75F2DA2A-1741-445A-9FA7-B63A81E4BD7F',
  'name': 'Restroom - Accessible',
  'categories': ['Accessibility', 'Restrooms']},
 {'id': '79247274-A3FB-42C4-9361-45A2BFADE78C',
  'name': 'Scenic View/Photo Spot',
  'categories': ['Recreation']},
 {'id': '66F39143-96B7-44BC-BE90-EB44C361B448',
  'name': 'Sewage Dump Station - Boat/RV',
  'categories': ['Convenience']},
 {'id': '94E21603-85F3-48C5-96B6-556E46FA2518',
  'name': 'Showers',
  'categories': ['Convenience']},
 {'id': '460AECEB-2158-47B4-8DAC-40041649C0F3',
  'name': 'Supplies - Camping/Outdoor',
  'categories': ['Souvenirs and Supplies']},
 {'id': '94006F6C-4EEF-489C-B8E6-FF1565E25F84',
  'name': 'Supplies - General',
  'categories': ['Souvenirs and Supplies']},
 {'id': '1FF653F6-1F20-425C-A16A-B8D6210CD759',
  'name': 'Tactile Exhibit',
  'categories': ['Accessibility']},
 {'id': '343F0388-C62A-4FEB-A790-E73253ECDDB2',
  'name': 'Telephone',
  'categories': ['Convenience']},
 {'id': 'A5EA8D15-1DFE-43D4-B2C4-B76DD927CE50',
  'name': 'Theater/Auditorium',
  'categories': ['Interpretive']},
 {'id': 'C7577040-41BF-4948-9521-7044E09ABF7C',
  'name': 'Ticket Sales',
  'categories': ['Permits and Passes']},
 {'id': 'CC4A51EF-1CB8-4625-9A9B-3AC77AF2F668',
  'name': 'Toilet - Flush',
  'categories': ['Restrooms']},
 {'id': 'F84C0528-0D1A-45A2-B644-B3C059B3D224',
  'name': 'Toilet - Vault/Composting',
  'categories': ['Restrooms']},
 {'id': '39BE9614-4284-4B29-A650-AB2E7215C58B',
  'name': 'Trailhead',
  'categories': ['Hiking', 'Recreation']},
 {'id': '4EDE1652-84E4-4219-8D20-26317D4B61DA',
  'name': 'Trash Dumpster',
  'categories': ['Convenience']},
 {'id': '4D4C1C32-793D-4440-8098-DBCA0126EDFD',
  'name': 'Trash/Litter Receptacles',
  'categories': ['Convenience']},
 {'id': '23682251-700A-4DE2-8FD8-BD680F53DF82',
  'name': 'Water - Bottle-Filling Station',
  'categories': ['Convenience', 'Drinking Water', 'Safety']},
 {'id': '9A652919-D548-4850-8053-798CDC2C762B',
  'name': 'Water - Drinking/Potable',
  'categories': ['Convenience', 'Drinking Water', 'Safety']},
 {'id': 'EAB59B1F-2FA1-4545-A322-2C19149AF7FC',
  'name': 'Wheelchair Accessible',
  'categories': ['Accessibility']},
 {'id': '1CF3D18E-C6A7-4462-9990-86B59383A9C3',
  'name': 'Wheelchairs Available',
  'categories': ['Accessibility']}]

In [36]:
lang_chat(question)

'Bryce Canyon National Park offers amenities such as benches/seating, information kiosk/bulletin board, parking - auto, picnic table, restroom, scenic view/photo spot, and trailhead.'

In [37]:
gpt_chat(question)

'Bryce Canyon National Park in Utah offers amenities such as campgrounds, lodging facilities, visitor centers, hiking trails, scenic overlooks, picnic areas, and ranger-led programs. There are also restaurants, gift shops, and restrooms available within the park.'

State

In [38]:
question ='What state is everglades in?'
get_context(question, model)

[{'id': '5EA02193-276A-4037-B7DB-5765A56935FD',
  'url': 'https://www.nps.gov/ever/index.htm',
  'fullName': 'Everglades National Park',
  'parkCode': 'ever',
  'description': 'Everglades National Park protects an unparalleled landscape that provides important habitat for numerous rare and endangered species like the manatee, American crocodile, and the elusive Florida panther. An international treasure as well - a World Heritage Site, International Biosphere Reserve, a Wetland of International Importance, and a specially protected area under the Cartagena Treaty.',
  'latitude': '25.37294225',
  'longitude': '-80.88200301',
  'latLong': 'lat:25.37294225, long:-80.88200301',
  'activities': [{'id': '5F723BAD-7359-48FC-98FA-631592256E35',
    'name': 'Auto and ATV'},
   {'id': '0B4A5320-216D-451A-9990-626E1D5ACE28', 'name': 'Scenic Driving'},
   {'id': '13A57703-BB1A-41A2-94B8-53B692EB7238', 'name': 'Astronomy'},
   {'id': 'D37A0003-8317-4F04-8FB0-4CF0A272E195', 'name': 'Stargazing'},
   {'id': '7CE6E935-F839-4FEC-A63E-052B1DEF39D2', 'name': 'Biking'},
   {'id': '8D778629-F603-4C50-A121-6F4BB2FE2C4B', 'name': 'Road Biking'},
   {'id': '071BA73C-1D3C-46D4-A53C-00D5602F7F0E', 'name': 'Boating'},
   {'id': 'E0E4CE55-3119-46DE-86EB-6817CD8D5F30', 'name': 'Motorized Boating'},
   {'id': 'BB0B8CD0-BF4C-4517-9980-CFE2D149C7B4', 'name': 'Sailing'},
   {'id': 'A510F02B-8938-4679-A4F9-76580BCAE9C7', 'name': 'Boat Tour'},
   {'id': 'A59947B7-3376-49B4-AD02-C0423E08C5F7', 'name': 'Camping'},
   {'id': '4A58AF13-E8FB-4530-B41A-97DF0B0C77B7',
    'name': 'Backcountry Camping'},
   {'id': '907E8125-15E4-483C-8EAD-B9FA1E85C6F8',
    'name': 'Canoe or Kayak Camping'},
   {'id': '9159DF0F-951D-4AAE-9987-CEB3CE2A9ADA',
    'name': 'Car or Front Country Camping'},
   {'id': '7CFF5F03-5ECC-4F5A-8572-75D1F0976C0C', 'name': 'Group Camping'},
   {'id': 'C5C5971C-E325-4CEB-8C81-EE49A881DF17', 'name': 'RV Camping'},
   {'id': 'C11D3746-5063-4BD0-B245-7178D1AD866C', 'name': 'Compass and GPS'},
   {'id': 'CA3641A0-FADC-497F-B036-3FE426D0DDCC', 'name': 'Geocaching'},
   {'id': 'AE42B46C-E4B7-4889-A122-08FE180371AE', 'name': 'Fishing'},
   {'id': '25FB188F-5AAD-459A-9092-28A9801709FF',
    'name': 'Freshwater Fishing'},
   {'id': '17411C8D-5769-4D0F-ABD1-52ED03840C18', 'name': 'Saltwater Fishing'},
   {'id': '1DFACD97-1B9C-4F5A-80F2-05593604799E', 'name': 'Food'},
   {'id': 'C6D3230A-2CEA-4AFE-BFF3-DC1E2C2C4BB4', 'name': 'Picnicking'},
   {'id': 'B33DC9B6-0B7D-4322-BAD7-A13A34C584A3', 'name': 'Guided Tours'},
   {'id': 'A0631906-9672-4583-91DE-113B93DB6B6E',
    'name': 'Self-Guided Tours - Walking'},
   {'id': 'C7D5A145-F8EB-4C37-9E92-2F6C6206B196',
    'name': 'Self-Guided Tours - Auto'},
   {'id': '3DE599E2-22ED-40BF-B383-EDA073563C1E',
    'name': 'Bus/Shuttle Guided Tour'},
   {'id': '5A241412-0CFB-497A-9B5F-0AB8C03CDE72', 'name': 'Boat Tour'},
   {'id': '42FD78B9-2B90-4AA9-BC43-F10E9FEA8B5A', 'name': 'Hands-On'},
   {'id': '31F88DA6-696F-441F-89CF-D7B1415C4CB9', 'name': 'Citizen Science'},
   {'id': '9456A40A-AF75-4AD3-8BE1-79C4A7DBEDFC',
    'name': 'Volunteer Vacation'},
   {'id': 'BFF8C027-7C8F-480B-A5F8-CD8CE490BFBA', 'name': 'Hiking'},
   {'id': '7C37B79B-D02D-49EB-9020-3DB8299B748A',
    'name': 'Backcountry Hiking'},
   {'id': '45261C0A-00D8-4C27-A1F8-029F933A0D34',
    'name': 'Front-Country Hiking'},
   {'id': '4D224BCA-C127-408B-AC75-A51563C42411', 'name': 'Paddling'},
   {'id': '21DB3AFC-8AAC-4665-BC1F-7198C0685983', 'name': 'Canoeing'},
   {'id': '256543C7-4322-48B3-8978-765E89AA9431',
    'name': 'Canoe or Kayak Camping'},
   {'id': 'F353A9ED-4A08-456E-8DEC-E61974D0FEB6', 'name': 'Kayaking'},
   {'id': 'DF4A35E0-7983-4A3E-BC47-F37B872B0F25',
    'name': 'Junior Ranger Program'},
   {'id': '0B685688-3405-4E2A-ABBA-E3069492EC50', 'name': 'Wildlife Watching'},
   {'id': '5A2C91D1-50EC-4B24-8BED-A2E11A1892DF', 'name': 'Birdwatching'},
   {'id': '0C0D142F-06B5-4BE1-8B44-491B90F93DEB', 'name': 'Park Film'},
   {'id': 'C8F98B28-3C10-41AE-AA99-092B3B398C43', 'name': 'Museum Exhibits'},
   {'id': '24380E3F-AD9D-4E38-BF13-C8EEB21893E7', 'name': 'Shopping'},
   {'id': '467DC8B8-0B7D-436D-A026-80A22358F615',
    'name': 'Bookstore and Park Store'},
   {'id': '43800AD1-D439-40F3-AAB3-9FB651FE45BB',
    'name': 'Gift Shop and Souvenirs'}],
  'topics': [{'id': '69693007-2DF2-4EDE-BB3B-A25EBA72BDF5',
    'name': 'Architecture and Building'},
   {'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B', 'name': 'Archeology'},
   {'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370', 'name': 'Arts'},
   {'id': '7F12224B-217A-4B07-A4A2-636B1CE7F221',
    'name': 'Colonization and Settlement'},
   {'id': '3B0D607D-9933-425A-BFA0-21529AC4734C', 'name': 'Military'},
   {'id': 'B145FAB8-5462-4FE2-964E-464D3A5E7F96', 'name': 'Artillery'},
   {'id': '97CCB419-196C-4B95-BB3A-621458F78415', 'name': 'US Army'},
   {'id': '2ACF7D12-91EA-4981-A1B7-AD0A186B6800', 'name': 'Armories'},
   {'id': 'A1BAF33E-EA84-4608-A888-4CEE9541F027',
    'name': 'Native American Heritage'},
   {'id': '3CDB67A9-1EAC-408D-88EC-F26FA35E90AF',
    'name': 'Schools and Education'},
   {'id': '40C0866A-3890-41A4-84CA-5935DEE181AE', 'name': 'Social Movements'},
   {'id': '4C0EBDE7-EB73-4252-84D9-0650974EC3E5',
    'name': 'Conservation Movement'},
   {'id': '27BF8807-54EA-4A3D-B073-AA7AA361CD7E',
    'name': 'Wars and Conflicts'},
   {'id': 'A764E57D-9925-4855-8D66-C60357946FC3', 'name': 'Cold War'},
   {'id': '0D00073E-18C3-46E5-8727-2F87B112DDC6', 'name': 'Animals'},
   {'id': '921D1471-5F6B-47D5-918D-389E7106083A',
    'name': 'Alligators or Crocodiles'},
   {'id': '957EF2BD-AC6C-4B7B-BD9A-87593ADC6691', 'name': 'Birds'},
   {'id': '2539614A-9646-446E-8251-34D3AAE068FA', 'name': 'Cats (wild)'},
   {'id': '1608649A-E7D7-4529-BD83-074C90F9FB68', 'name': 'Fish'},
   {'id': '393F60FB-80D6-46F7-B0FB-BBF3C90F59FD',
    'name': 'Tortoises and Turtles'},
   {'id': '4DC11D06-00F1-4A01-81D0-89CCCCE4FF50', 'name': 'Climate Change'},
   {'id': '46FC5CBD-9AD5-48F1-B4DA-1357031B1D2E',
    'name': 'Coasts, Islands and Atolls'},
   {'id': 'F79C1242-80FF-40F0-A0C1-5FFCBA172EC0',
    'name': 'Estuaries and Mangroves'},
   {'id': '04A39AB8-DD02-432F-AE5F-BA1267D41A0D', 'name': 'Fire'},
   {'id': 'F0F97E32-2F29-41B4-AF98-9FBE8DAB36B1', 'name': 'Geology'},
   {'id': '94262026-92F5-48E9-90EF-01CEAEFBA4FF', 'name': 'Grasslands'},
   {'id': '1AEDC86F-5792-487F-8CDF-9E92CAB97ACE', 'name': 'Prairies'},
   {'id': 'F8C2FE93-DEB3-4B12-9A87-913E3E6B448D', 'name': 'Natural Sounds'},
   {'id': 'A7359FC4-DAD8-45F5-AF15-7FF62F816ED3', 'name': 'Night Sky'},
   {'id': '0E6D8503-CB65-467F-BCD6-C6D9E28A4E0B', 'name': 'Oceans'},
   {'id': 'A155238F-0DD2-4610-9B87-05FCE1C59283',
    'name': 'River and Riparian'},
   {'id': '9C9FCBB6-360B-4743-8155-6F9341CBE01B', 'name': 'Scenic Views'},
   {'id': '5BE55D7F-BDB6-4E3D-AC35-2D8EBB974417', 'name': 'Trails'},
   {'id': '596BAA6D-F66B-4348-8433-FEFF35A8005E', 'name': 'Water Trails'},
   {'id': '78E4F4AC-AF97-435A-8C2C-7FB8D67516ED', 'name': 'Unique Species'},
   {'id': '996BEDAE-CB23-4003-B008-3A1F46A72263', 'name': 'Rare'},
   {'id': '489D6333-FD72-44DF-83B0-3D4412DD0A75', 'name': 'Endangered'},
   {'id': '1365C347-952C-475A-B755-731DD523C195', 'name': 'Wetlands'},
   {'id': 'FD0BA21A-5F69-4688-9D4B-856DA242DC78', 'name': 'Marshes'},
   {'id': 'B85866E2-0897-4000-9040-605CA335804F', 'name': 'Wilderness'}],
  'states': 'FL',
  'contacts': {'phoneNumbers': [{'phoneNumber': '3052427700',
     'description': '',
     'extension': '',
     'type': 'Voice'},
    {'phoneNumber': '3052427728',
     'description': '',
     'extension': '',
     'type': 'Fax'}],
   'emailAddresses': [{'description': '',
     'emailAddress': 'ever_information@nps.gov'}]},
  'entranceFees': [{'cost': '35.00',
    'description': 'Admits the passholder and passengers of a single vehicle or vessel. Good for 7 consecutive days at all park entrances.',
    'title': 'Entrance - Private Vehicle'},
   {'cost': '30.00',
    'description': 'Good for 7 consecutive days at all park entrances.',
    'title': 'Entrance - Motorcycle'},
   {'cost': '20.00',
    'description': 'Good for 7 consecutive days at all park entrances. Admits one individual hiker, bicyclist, pedestrian, or human-powered paddlecraft, when not arriving in a vehicle or vessel. Individuals 15 years old and younger, are admitted free of charge.',
    'title': 'Entrance - Per Person'},
   {'cost': '0.00',
    'description': 'All accredited educational and scientific institutions are eligible to receive free entrance to the park. Bringing your classroom to the park can present many unique learning opportunities and novel ways for your students to advance their studies. The Federal Lands Recreation Enhancement Act (FLREA), Public Law 108-447, provides the National Park Service statutory authority to allow “outings conducted for non-commercial educational purposes by schools or bona fide academic institutions.”',
    'title': 'Entrance - Education/Academic Groups'},
   {'cost': '300.00',
    'description': 'A commercial tour is defined as persons traveling on an itinerary that has been packaged, priced or sold for leisure recreational purposes by an organization that realizes financial gain through the provisions of the service. Entrance fees are charges based on the seating capacity of the vehicle. Commercial entry good for 7 days as long as its the same passenger group.',
    'title': 'Commercial Entrance - Motor Coach'},
   {'cost': '200.00',
    'description': 'A commercial tour is defined as persons traveling on an itinerary that has been packaged, priced or sold for leisure recreational purposes by an organization that realizes financial gain through the provisions of the service. Entrance fees are charges based on the seating capacity of the vehicle. Commercial entry good for 7 days as long as its the same passenger group.',
    'title': 'Commercial Entrance - Mini-bus'},
   {'cost': '125.00',
    'description': 'A commercial tour is defined as persons traveling on an itinerary that has been packaged, priced or sold for leisure recreational purposes by an organization that realizes financial gain through the provisions of the service. Entrance fees are charges based on the seating capacity of the vehicle. Commercial entry good for 7 days as long as its the same passenger group.',
    'title': 'Commercial Entrance - Van'}],
  'entrancePasses': [{'cost': '70.00',
    'description': 'The Everglades Annual Pass admits the pass holder, passenger on one motorcycle, or passengers of a single vehicle or vessel to Everglades National Park.',
    'title': 'Annual Entrance - Park'}],
  'fees': [],
  'directionsInfo': 'Directions to Ernest Coe Visitor Center 40001 State Road 9336, Homestead, FL 33034 Visitors coming from the Miami area and points north should take the Florida Turnpike (Route 821) south until it ends merging with U.S. 1 at Florida City. Turn right at the first traffic light onto Palm Drive (State Road 9336/SW 344th St.) and follow the signs to the park. Visitors driving north from the Florida Keys should turn left on Palm Drive in Florida City and follow the signs to the park.',
  'directionsUrl': 'http://www.nps.gov/ever/planyourvisit/directions.htm',
  'operatingHours': [{'exceptions': [],
    'description': 'Everglades National Park is open 7 days a week, 24 hours a day. Park entrance is always open but staffed from 8:00 a.m. to 4:30 p.m.',
    'standardHours': {'wednesday': 'All Day',
     'monday': 'All Day',
     'thursday': 'All Day',
     'sunday': 'All Day',
     'tuesday': 'All Day',
     'friday': 'All Day',
     'saturday': 'All Day'},
    'name': 'Everglades National Park'}],
  'addresses': [{'postalCode': '33034',
    'city': 'Homestead',
    'stateCode': 'FL',
    'countryCode': 'US',
    'provinceTerritoryCode': '',
    'line1': '40001 State Road 9336',
    'type': 'Physical',
    'line3': '',
    'line2': ''},
   {'postalCode': '33034-6733',
    'city': 'Homestead',
    'stateCode': 'FL',
    'countryCode': 'US',
    'provinceTerritoryCode': '',
    'line1': '40001 State Road 9336',
    'type': 'Mailing',
    'line3': '',
    'line2': ''}],
  'images': [{'credit': 'NPS Photo by Miguel Salas',
    'title': 'Cypress Tree Sunrise',
    'altText': "A sunset creates a silhouette of a cypress tree with needle-like leaves that is shaped like an 'N'.",
    'caption': 'Cypress Tree Sunrise (2020 Photo Contest)',
    'url': 'https://www.nps.gov/common/uploads/structured_data/17EC840E-9926-2E09-F2DD47A282915BBB.jpg'},
   {'credit': 'NPS Photo',
    'title': 'Nine Mile Pond',
    'altText': 'Two canoes at Nine Mile Pond during sunset.',
    'caption': 'A meeting ground of marsh and mangrove environments. You may see alligators, wading birds, turtles, and fish.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C854681-1DD8-B71B-0BA4F6D9379336DF.jpg'},
   {'credit': 'NPS Photo',
    'title': 'American Alligator',
    'altText': 'An American Alligator high walks the Anhinga Trail.',
    'caption': 'An American Alligator high walks the Anhinga Trail.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C8547ED-1DD8-B71B-0B596F29F0A9A60B.jpg'},
   {'credit': 'NPS Photo',
    'title': 'Shark Valley Tram and Bicycle Road',
    'altText': 'Two visitors bike along the road in Shark Valley.',
    'caption': 'Biking is a great way to experience the quiet beauty of the Everglades.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85E60F-1DD8-B71B-0BAB4F7583E96025.jpg'},
   {'credit': 'NPS Photo',
    'title': 'Transition from Sawgrass to Florida Bay',
    'altText': 'An aerial view of the landscape transition from Sawgrass to Florida Bay.',
    'caption': 'An aerial view of the landscape transition from Sawgrass to Florida Bay.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85E70B-1DD8-B71B-0B7C75649CCDB907.jpg'},
   {'credit': 'NPS Photo',
    'title': 'Camping at Long Pine Key',
    'altText': 'Three tents are put up along the Long Pine Key campsite.',
    'caption': 'Long Pine Key Campground is open seasonally from November through May. It is located seven miles (11 km) from the main entrance, just off the main road.',
    'url': 'https://www.nps.gov/common/uploads/structured_data/3C85F532-1DD8-B71B-0BFC5BB51D8AB675.jpg'}],
  'weatherInfo': 'The climate in Florida is known to be mild and sunny.The average annual temperatures for South Florida and the Keys range from 74° to 77°F (23° to 25°C). There are two seasons at the Everglades National Park: the wet season and the dry season. The wet season runs from Mid-May to November and the dry season runs from December to mid-May.',
  'name': 'Everglades',
  'designation': 'National Park',
  'multimedia': [],
  'relevanceScore': 1.0}]

In [39]:
lang_chat(question)

'Everglades National Park is located in the state of Florida (FL).'

In [40]:
gpt_chat(question)

'Everglades National Park is located in the state of Florida.'